package org.fbi.hmfsjz.repository.model;

import java.math.BigDecimal;

public class HmfsJzDraw {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.PKID
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.BILLNO
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.BILL_STS_CODE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String billStsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.BILL_STS_TITLE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String billStsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.HOUSE_ID
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.HOUSE_AREA
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String houseArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.STANDARD
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String standard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.TXN_AMT
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private BigDecimal txnAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.AREA_ACCOUNT
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String areaAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.HOUSE_ACCOUNT
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String houseAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.RESERVE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String reserve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.OPER_DATE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.OPER_TIME
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.OPER_ID
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.REMARK
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.CFM_TXN_CODE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String cfmTxnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.QRY_TXN_CODE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String qryTxnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.ACT_SERIAL_NO
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String actSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.BOOK_TYPE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String bookType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.STS_FLAG
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String stsFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.RELATE_BILLNO
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String relateBillno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.DEPT_ID
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.BANK_CFM_DATE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String bankCfmDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.PAY_MONEY
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private BigDecimal payMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_DRAW.HOUSE_LOCATION
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    private String houseLocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.PKID
     *
     * @return the value of FIS.HMFS_JM_DRAW.PKID
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.PKID
     *
     * @param pkid the value for FIS.HMFS_JM_DRAW.PKID
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.BILLNO
     *
     * @return the value of FIS.HMFS_JM_DRAW.BILLNO
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.BILLNO
     *
     * @param billno the value for FIS.HMFS_JM_DRAW.BILLNO
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.BILL_STS_CODE
     *
     * @return the value of FIS.HMFS_JM_DRAW.BILL_STS_CODE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getBillStsCode() {
        return billStsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.BILL_STS_CODE
     *
     * @param billStsCode the value for FIS.HMFS_JM_DRAW.BILL_STS_CODE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setBillStsCode(String billStsCode) {
        this.billStsCode = billStsCode == null ? null : billStsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.BILL_STS_TITLE
     *
     * @return the value of FIS.HMFS_JM_DRAW.BILL_STS_TITLE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getBillStsTitle() {
        return billStsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.BILL_STS_TITLE
     *
     * @param billStsTitle the value for FIS.HMFS_JM_DRAW.BILL_STS_TITLE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setBillStsTitle(String billStsTitle) {
        this.billStsTitle = billStsTitle == null ? null : billStsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.HOUSE_ID
     *
     * @return the value of FIS.HMFS_JM_DRAW.HOUSE_ID
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.HOUSE_ID
     *
     * @param houseId the value for FIS.HMFS_JM_DRAW.HOUSE_ID
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setHouseId(String houseId) {
        this.houseId = houseId == null ? null : houseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.HOUSE_AREA
     *
     * @return the value of FIS.HMFS_JM_DRAW.HOUSE_AREA
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getHouseArea() {
        return houseArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.HOUSE_AREA
     *
     * @param houseArea the value for FIS.HMFS_JM_DRAW.HOUSE_AREA
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setHouseArea(String houseArea) {
        this.houseArea = houseArea == null ? null : houseArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.STANDARD
     *
     * @return the value of FIS.HMFS_JM_DRAW.STANDARD
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.STANDARD
     *
     * @param standard the value for FIS.HMFS_JM_DRAW.STANDARD
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.TXN_AMT
     *
     * @return the value of FIS.HMFS_JM_DRAW.TXN_AMT
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public BigDecimal getTxnAmt() {
        return txnAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.TXN_AMT
     *
     * @param txnAmt the value for FIS.HMFS_JM_DRAW.TXN_AMT
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setTxnAmt(BigDecimal txnAmt) {
        this.txnAmt = txnAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.AREA_ACCOUNT
     *
     * @return the value of FIS.HMFS_JM_DRAW.AREA_ACCOUNT
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getAreaAccount() {
        return areaAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.AREA_ACCOUNT
     *
     * @param areaAccount the value for FIS.HMFS_JM_DRAW.AREA_ACCOUNT
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setAreaAccount(String areaAccount) {
        this.areaAccount = areaAccount == null ? null : areaAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.HOUSE_ACCOUNT
     *
     * @return the value of FIS.HMFS_JM_DRAW.HOUSE_ACCOUNT
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getHouseAccount() {
        return houseAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.HOUSE_ACCOUNT
     *
     * @param houseAccount the value for FIS.HMFS_JM_DRAW.HOUSE_ACCOUNT
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setHouseAccount(String houseAccount) {
        this.houseAccount = houseAccount == null ? null : houseAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.RESERVE
     *
     * @return the value of FIS.HMFS_JM_DRAW.RESERVE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getReserve() {
        return reserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.RESERVE
     *
     * @param reserve the value for FIS.HMFS_JM_DRAW.RESERVE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setReserve(String reserve) {
        this.reserve = reserve == null ? null : reserve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.OPER_DATE
     *
     * @return the value of FIS.HMFS_JM_DRAW.OPER_DATE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.OPER_DATE
     *
     * @param operDate the value for FIS.HMFS_JM_DRAW.OPER_DATE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.OPER_TIME
     *
     * @return the value of FIS.HMFS_JM_DRAW.OPER_TIME
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.OPER_TIME
     *
     * @param operTime the value for FIS.HMFS_JM_DRAW.OPER_TIME
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime == null ? null : operTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.OPER_ID
     *
     * @return the value of FIS.HMFS_JM_DRAW.OPER_ID
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.OPER_ID
     *
     * @param operId the value for FIS.HMFS_JM_DRAW.OPER_ID
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.REMARK
     *
     * @return the value of FIS.HMFS_JM_DRAW.REMARK
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.REMARK
     *
     * @param remark the value for FIS.HMFS_JM_DRAW.REMARK
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.CFM_TXN_CODE
     *
     * @return the value of FIS.HMFS_JM_DRAW.CFM_TXN_CODE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getCfmTxnCode() {
        return cfmTxnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.CFM_TXN_CODE
     *
     * @param cfmTxnCode the value for FIS.HMFS_JM_DRAW.CFM_TXN_CODE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setCfmTxnCode(String cfmTxnCode) {
        this.cfmTxnCode = cfmTxnCode == null ? null : cfmTxnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.QRY_TXN_CODE
     *
     * @return the value of FIS.HMFS_JM_DRAW.QRY_TXN_CODE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getQryTxnCode() {
        return qryTxnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.QRY_TXN_CODE
     *
     * @param qryTxnCode the value for FIS.HMFS_JM_DRAW.QRY_TXN_CODE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setQryTxnCode(String qryTxnCode) {
        this.qryTxnCode = qryTxnCode == null ? null : qryTxnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.ACT_SERIAL_NO
     *
     * @return the value of FIS.HMFS_JM_DRAW.ACT_SERIAL_NO
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getActSerialNo() {
        return actSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.ACT_SERIAL_NO
     *
     * @param actSerialNo the value for FIS.HMFS_JM_DRAW.ACT_SERIAL_NO
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setActSerialNo(String actSerialNo) {
        this.actSerialNo = actSerialNo == null ? null : actSerialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.BOOK_TYPE
     *
     * @return the value of FIS.HMFS_JM_DRAW.BOOK_TYPE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getBookType() {
        return bookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.BOOK_TYPE
     *
     * @param bookType the value for FIS.HMFS_JM_DRAW.BOOK_TYPE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setBookType(String bookType) {
        this.bookType = bookType == null ? null : bookType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.STS_FLAG
     *
     * @return the value of FIS.HMFS_JM_DRAW.STS_FLAG
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getStsFlag() {
        return stsFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.STS_FLAG
     *
     * @param stsFlag the value for FIS.HMFS_JM_DRAW.STS_FLAG
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setStsFlag(String stsFlag) {
        this.stsFlag = stsFlag == null ? null : stsFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.RELATE_BILLNO
     *
     * @return the value of FIS.HMFS_JM_DRAW.RELATE_BILLNO
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getRelateBillno() {
        return relateBillno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.RELATE_BILLNO
     *
     * @param relateBillno the value for FIS.HMFS_JM_DRAW.RELATE_BILLNO
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setRelateBillno(String relateBillno) {
        this.relateBillno = relateBillno == null ? null : relateBillno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.DEPT_ID
     *
     * @return the value of FIS.HMFS_JM_DRAW.DEPT_ID
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.DEPT_ID
     *
     * @param deptId the value for FIS.HMFS_JM_DRAW.DEPT_ID
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.BANK_CFM_DATE
     *
     * @return the value of FIS.HMFS_JM_DRAW.BANK_CFM_DATE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getBankCfmDate() {
        return bankCfmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.BANK_CFM_DATE
     *
     * @param bankCfmDate the value for FIS.HMFS_JM_DRAW.BANK_CFM_DATE
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setBankCfmDate(String bankCfmDate) {
        this.bankCfmDate = bankCfmDate == null ? null : bankCfmDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.PAY_MONEY
     *
     * @return the value of FIS.HMFS_JM_DRAW.PAY_MONEY
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public BigDecimal getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.PAY_MONEY
     *
     * @param payMoney the value for FIS.HMFS_JM_DRAW.PAY_MONEY
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setPayMoney(BigDecimal payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_DRAW.HOUSE_LOCATION
     *
     * @return the value of FIS.HMFS_JM_DRAW.HOUSE_LOCATION
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public String getHouseLocation() {
        return houseLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_DRAW.HOUSE_LOCATION
     *
     * @param houseLocation the value for FIS.HMFS_JM_DRAW.HOUSE_LOCATION
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    public void setHouseLocation(String houseLocation) {
        this.houseLocation = houseLocation == null ? null : houseLocation.trim();
    }
}