package org.fbi.hmfsjz.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class HmfsJzInterestExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public HmfsJzInterestExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andInterestIsNull() {
            addCriterion("INTEREST is null");
            return (Criteria) this;
        }

        public Criteria andInterestIsNotNull() {
            addCriterion("INTEREST is not null");
            return (Criteria) this;
        }

        public Criteria andInterestEqualTo(BigDecimal value) {
            addCriterion("INTEREST =", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotEqualTo(BigDecimal value) {
            addCriterion("INTEREST <>", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThan(BigDecimal value) {
            addCriterion("INTEREST >", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INTEREST >=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThan(BigDecimal value) {
            addCriterion("INTEREST <", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INTEREST <=", value, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestIn(List<BigDecimal> values) {
            addCriterion("INTEREST in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotIn(List<BigDecimal> values) {
            addCriterion("INTEREST not in", values, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INTEREST between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INTEREST not between", value1, value2, "interest");
            return (Criteria) this;
        }

        public Criteria andInterestNoIsNull() {
            addCriterion("INTEREST_NO is null");
            return (Criteria) this;
        }

        public Criteria andInterestNoIsNotNull() {
            addCriterion("INTEREST_NO is not null");
            return (Criteria) this;
        }

        public Criteria andInterestNoEqualTo(String value) {
            addCriterion("INTEREST_NO =", value, "interestNo");
            return (Criteria) this;
        }

        public Criteria andInterestNoNotEqualTo(String value) {
            addCriterion("INTEREST_NO <>", value, "interestNo");
            return (Criteria) this;
        }

        public Criteria andInterestNoGreaterThan(String value) {
            addCriterion("INTEREST_NO >", value, "interestNo");
            return (Criteria) this;
        }

        public Criteria andInterestNoGreaterThanOrEqualTo(String value) {
            addCriterion("INTEREST_NO >=", value, "interestNo");
            return (Criteria) this;
        }

        public Criteria andInterestNoLessThan(String value) {
            addCriterion("INTEREST_NO <", value, "interestNo");
            return (Criteria) this;
        }

        public Criteria andInterestNoLessThanOrEqualTo(String value) {
            addCriterion("INTEREST_NO <=", value, "interestNo");
            return (Criteria) this;
        }

        public Criteria andInterestNoLike(String value) {
            addCriterion("INTEREST_NO like", value, "interestNo");
            return (Criteria) this;
        }

        public Criteria andInterestNoNotLike(String value) {
            addCriterion("INTEREST_NO not like", value, "interestNo");
            return (Criteria) this;
        }

        public Criteria andInterestNoIn(List<String> values) {
            addCriterion("INTEREST_NO in", values, "interestNo");
            return (Criteria) this;
        }

        public Criteria andInterestNoNotIn(List<String> values) {
            addCriterion("INTEREST_NO not in", values, "interestNo");
            return (Criteria) this;
        }

        public Criteria andInterestNoBetween(String value1, String value2) {
            addCriterion("INTEREST_NO between", value1, value2, "interestNo");
            return (Criteria) this;
        }

        public Criteria andInterestNoNotBetween(String value1, String value2) {
            addCriterion("INTEREST_NO not between", value1, value2, "interestNo");
            return (Criteria) this;
        }

        public Criteria andHouseAccountIsNull() {
            addCriterion("HOUSE_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andHouseAccountIsNotNull() {
            addCriterion("HOUSE_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andHouseAccountEqualTo(String value) {
            addCriterion("HOUSE_ACCOUNT =", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountNotEqualTo(String value) {
            addCriterion("HOUSE_ACCOUNT <>", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountGreaterThan(String value) {
            addCriterion("HOUSE_ACCOUNT >", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountGreaterThanOrEqualTo(String value) {
            addCriterion("HOUSE_ACCOUNT >=", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountLessThan(String value) {
            addCriterion("HOUSE_ACCOUNT <", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountLessThanOrEqualTo(String value) {
            addCriterion("HOUSE_ACCOUNT <=", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountLike(String value) {
            addCriterion("HOUSE_ACCOUNT like", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountNotLike(String value) {
            addCriterion("HOUSE_ACCOUNT not like", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountIn(List<String> values) {
            addCriterion("HOUSE_ACCOUNT in", values, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountNotIn(List<String> values) {
            addCriterion("HOUSE_ACCOUNT not in", values, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountBetween(String value1, String value2) {
            addCriterion("HOUSE_ACCOUNT between", value1, value2, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountNotBetween(String value1, String value2) {
            addCriterion("HOUSE_ACCOUNT not between", value1, value2, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseIdIsNull() {
            addCriterion("HOUSE_ID is null");
            return (Criteria) this;
        }

        public Criteria andHouseIdIsNotNull() {
            addCriterion("HOUSE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andHouseIdEqualTo(String value) {
            addCriterion("HOUSE_ID =", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotEqualTo(String value) {
            addCriterion("HOUSE_ID <>", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThan(String value) {
            addCriterion("HOUSE_ID >", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThanOrEqualTo(String value) {
            addCriterion("HOUSE_ID >=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThan(String value) {
            addCriterion("HOUSE_ID <", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThanOrEqualTo(String value) {
            addCriterion("HOUSE_ID <=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLike(String value) {
            addCriterion("HOUSE_ID like", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotLike(String value) {
            addCriterion("HOUSE_ID not like", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdIn(List<String> values) {
            addCriterion("HOUSE_ID in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotIn(List<String> values) {
            addCriterion("HOUSE_ID not in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdBetween(String value1, String value2) {
            addCriterion("HOUSE_ID between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotBetween(String value1, String value2) {
            addCriterion("HOUSE_ID not between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseLocationIsNull() {
            addCriterion("HOUSE_LOCATION is null");
            return (Criteria) this;
        }

        public Criteria andHouseLocationIsNotNull() {
            addCriterion("HOUSE_LOCATION is not null");
            return (Criteria) this;
        }

        public Criteria andHouseLocationEqualTo(String value) {
            addCriterion("HOUSE_LOCATION =", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationNotEqualTo(String value) {
            addCriterion("HOUSE_LOCATION <>", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationGreaterThan(String value) {
            addCriterion("HOUSE_LOCATION >", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationGreaterThanOrEqualTo(String value) {
            addCriterion("HOUSE_LOCATION >=", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationLessThan(String value) {
            addCriterion("HOUSE_LOCATION <", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationLessThanOrEqualTo(String value) {
            addCriterion("HOUSE_LOCATION <=", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationLike(String value) {
            addCriterion("HOUSE_LOCATION like", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationNotLike(String value) {
            addCriterion("HOUSE_LOCATION not like", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationIn(List<String> values) {
            addCriterion("HOUSE_LOCATION in", values, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationNotIn(List<String> values) {
            addCriterion("HOUSE_LOCATION not in", values, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationBetween(String value1, String value2) {
            addCriterion("HOUSE_LOCATION between", value1, value2, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationNotBetween(String value1, String value2) {
            addCriterion("HOUSE_LOCATION not between", value1, value2, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNull() {
            addCriterion("OWNER is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNotNull() {
            addCriterion("OWNER is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(String value) {
            addCriterion("OWNER =", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotEqualTo(String value) {
            addCriterion("OWNER <>", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThan(String value) {
            addCriterion("OWNER >", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("OWNER >=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThan(String value) {
            addCriterion("OWNER <", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThanOrEqualTo(String value) {
            addCriterion("OWNER <=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLike(String value) {
            addCriterion("OWNER like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotLike(String value) {
            addCriterion("OWNER not like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerIn(List<String> values) {
            addCriterion("OWNER in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotIn(List<String> values) {
            addCriterion("OWNER not in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerBetween(String value1, String value2) {
            addCriterion("OWNER between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotBetween(String value1, String value2) {
            addCriterion("OWNER not between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andBeforeAmtIsNull() {
            addCriterion("BEFORE_AMT is null");
            return (Criteria) this;
        }

        public Criteria andBeforeAmtIsNotNull() {
            addCriterion("BEFORE_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andBeforeAmtEqualTo(BigDecimal value) {
            addCriterion("BEFORE_AMT =", value, "beforeAmt");
            return (Criteria) this;
        }

        public Criteria andBeforeAmtNotEqualTo(BigDecimal value) {
            addCriterion("BEFORE_AMT <>", value, "beforeAmt");
            return (Criteria) this;
        }

        public Criteria andBeforeAmtGreaterThan(BigDecimal value) {
            addCriterion("BEFORE_AMT >", value, "beforeAmt");
            return (Criteria) this;
        }

        public Criteria andBeforeAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BEFORE_AMT >=", value, "beforeAmt");
            return (Criteria) this;
        }

        public Criteria andBeforeAmtLessThan(BigDecimal value) {
            addCriterion("BEFORE_AMT <", value, "beforeAmt");
            return (Criteria) this;
        }

        public Criteria andBeforeAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BEFORE_AMT <=", value, "beforeAmt");
            return (Criteria) this;
        }

        public Criteria andBeforeAmtIn(List<BigDecimal> values) {
            addCriterion("BEFORE_AMT in", values, "beforeAmt");
            return (Criteria) this;
        }

        public Criteria andBeforeAmtNotIn(List<BigDecimal> values) {
            addCriterion("BEFORE_AMT not in", values, "beforeAmt");
            return (Criteria) this;
        }

        public Criteria andBeforeAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BEFORE_AMT between", value1, value2, "beforeAmt");
            return (Criteria) this;
        }

        public Criteria andBeforeAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BEFORE_AMT not between", value1, value2, "beforeAmt");
            return (Criteria) this;
        }

        public Criteria andAfterAmtIsNull() {
            addCriterion("AFTER_AMT is null");
            return (Criteria) this;
        }

        public Criteria andAfterAmtIsNotNull() {
            addCriterion("AFTER_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andAfterAmtEqualTo(BigDecimal value) {
            addCriterion("AFTER_AMT =", value, "afterAmt");
            return (Criteria) this;
        }

        public Criteria andAfterAmtNotEqualTo(BigDecimal value) {
            addCriterion("AFTER_AMT <>", value, "afterAmt");
            return (Criteria) this;
        }

        public Criteria andAfterAmtGreaterThan(BigDecimal value) {
            addCriterion("AFTER_AMT >", value, "afterAmt");
            return (Criteria) this;
        }

        public Criteria andAfterAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AFTER_AMT >=", value, "afterAmt");
            return (Criteria) this;
        }

        public Criteria andAfterAmtLessThan(BigDecimal value) {
            addCriterion("AFTER_AMT <", value, "afterAmt");
            return (Criteria) this;
        }

        public Criteria andAfterAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AFTER_AMT <=", value, "afterAmt");
            return (Criteria) this;
        }

        public Criteria andAfterAmtIn(List<BigDecimal> values) {
            addCriterion("AFTER_AMT in", values, "afterAmt");
            return (Criteria) this;
        }

        public Criteria andAfterAmtNotIn(List<BigDecimal> values) {
            addCriterion("AFTER_AMT not in", values, "afterAmt");
            return (Criteria) this;
        }

        public Criteria andAfterAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AFTER_AMT between", value1, value2, "afterAmt");
            return (Criteria) this;
        }

        public Criteria andAfterAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AFTER_AMT not between", value1, value2, "afterAmt");
            return (Criteria) this;
        }

        public Criteria andBeginDateIsNull() {
            addCriterion("BEGIN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andBeginDateIsNotNull() {
            addCriterion("BEGIN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andBeginDateEqualTo(String value) {
            addCriterion("BEGIN_DATE =", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateNotEqualTo(String value) {
            addCriterion("BEGIN_DATE <>", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateGreaterThan(String value) {
            addCriterion("BEGIN_DATE >", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateGreaterThanOrEqualTo(String value) {
            addCriterion("BEGIN_DATE >=", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateLessThan(String value) {
            addCriterion("BEGIN_DATE <", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateLessThanOrEqualTo(String value) {
            addCriterion("BEGIN_DATE <=", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateLike(String value) {
            addCriterion("BEGIN_DATE like", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateNotLike(String value) {
            addCriterion("BEGIN_DATE not like", value, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateIn(List<String> values) {
            addCriterion("BEGIN_DATE in", values, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateNotIn(List<String> values) {
            addCriterion("BEGIN_DATE not in", values, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateBetween(String value1, String value2) {
            addCriterion("BEGIN_DATE between", value1, value2, "beginDate");
            return (Criteria) this;
        }

        public Criteria andBeginDateNotBetween(String value1, String value2) {
            addCriterion("BEGIN_DATE not between", value1, value2, "beginDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("END_DATE is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("END_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(String value) {
            addCriterion("END_DATE =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(String value) {
            addCriterion("END_DATE <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(String value) {
            addCriterion("END_DATE >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(String value) {
            addCriterion("END_DATE >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(String value) {
            addCriterion("END_DATE <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(String value) {
            addCriterion("END_DATE <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLike(String value) {
            addCriterion("END_DATE like", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotLike(String value) {
            addCriterion("END_DATE not like", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<String> values) {
            addCriterion("END_DATE in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<String> values) {
            addCriterion("END_DATE not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(String value1, String value2) {
            addCriterion("END_DATE between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(String value1, String value2) {
            addCriterion("END_DATE not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andCapitalIsNull() {
            addCriterion("CAPITAL is null");
            return (Criteria) this;
        }

        public Criteria andCapitalIsNotNull() {
            addCriterion("CAPITAL is not null");
            return (Criteria) this;
        }

        public Criteria andCapitalEqualTo(BigDecimal value) {
            addCriterion("CAPITAL =", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalNotEqualTo(BigDecimal value) {
            addCriterion("CAPITAL <>", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalGreaterThan(BigDecimal value) {
            addCriterion("CAPITAL >", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CAPITAL >=", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalLessThan(BigDecimal value) {
            addCriterion("CAPITAL <", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CAPITAL <=", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalIn(List<BigDecimal> values) {
            addCriterion("CAPITAL in", values, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalNotIn(List<BigDecimal> values) {
            addCriterion("CAPITAL not in", values, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CAPITAL between", value1, value2, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CAPITAL not between", value1, value2, "capital");
            return (Criteria) this;
        }

        public Criteria andRateIsNull() {
            addCriterion("RATE is null");
            return (Criteria) this;
        }

        public Criteria andRateIsNotNull() {
            addCriterion("RATE is not null");
            return (Criteria) this;
        }

        public Criteria andRateEqualTo(String value) {
            addCriterion("RATE =", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotEqualTo(String value) {
            addCriterion("RATE <>", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThan(String value) {
            addCriterion("RATE >", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateGreaterThanOrEqualTo(String value) {
            addCriterion("RATE >=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThan(String value) {
            addCriterion("RATE <", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLessThanOrEqualTo(String value) {
            addCriterion("RATE <=", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateLike(String value) {
            addCriterion("RATE like", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotLike(String value) {
            addCriterion("RATE not like", value, "rate");
            return (Criteria) this;
        }

        public Criteria andRateIn(List<String> values) {
            addCriterion("RATE in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotIn(List<String> values) {
            addCriterion("RATE not in", values, "rate");
            return (Criteria) this;
        }

        public Criteria andRateBetween(String value1, String value2) {
            addCriterion("RATE between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andRateNotBetween(String value1, String value2) {
            addCriterion("RATE not between", value1, value2, "rate");
            return (Criteria) this;
        }

        public Criteria andOperTimeIsNull() {
            addCriterion("OPER_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOperTimeIsNotNull() {
            addCriterion("OPER_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOperTimeEqualTo(String value) {
            addCriterion("OPER_TIME =", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotEqualTo(String value) {
            addCriterion("OPER_TIME <>", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeGreaterThan(String value) {
            addCriterion("OPER_TIME >", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_TIME >=", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLessThan(String value) {
            addCriterion("OPER_TIME <", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLessThanOrEqualTo(String value) {
            addCriterion("OPER_TIME <=", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLike(String value) {
            addCriterion("OPER_TIME like", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotLike(String value) {
            addCriterion("OPER_TIME not like", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeIn(List<String> values) {
            addCriterion("OPER_TIME in", values, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotIn(List<String> values) {
            addCriterion("OPER_TIME not in", values, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeBetween(String value1, String value2) {
            addCriterion("OPER_TIME between", value1, value2, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotBetween(String value1, String value2) {
            addCriterion("OPER_TIME not between", value1, value2, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNull() {
            addCriterion("OPER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNotNull() {
            addCriterion("OPER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOperIdEqualTo(String value) {
            addCriterion("OPER_ID =", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotEqualTo(String value) {
            addCriterion("OPER_ID <>", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThan(String value) {
            addCriterion("OPER_ID >", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_ID >=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThan(String value) {
            addCriterion("OPER_ID <", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThanOrEqualTo(String value) {
            addCriterion("OPER_ID <=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLike(String value) {
            addCriterion("OPER_ID like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotLike(String value) {
            addCriterion("OPER_ID not like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdIn(List<String> values) {
            addCriterion("OPER_ID in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotIn(List<String> values) {
            addCriterion("OPER_ID not in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdBetween(String value1, String value2) {
            addCriterion("OPER_ID between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotBetween(String value1, String value2) {
            addCriterion("OPER_ID not between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andTxnCodeIsNull() {
            addCriterion("TXN_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTxnCodeIsNotNull() {
            addCriterion("TXN_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnCodeEqualTo(String value) {
            addCriterion("TXN_CODE =", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotEqualTo(String value) {
            addCriterion("TXN_CODE <>", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeGreaterThan(String value) {
            addCriterion("TXN_CODE >", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_CODE >=", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeLessThan(String value) {
            addCriterion("TXN_CODE <", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeLessThanOrEqualTo(String value) {
            addCriterion("TXN_CODE <=", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeLike(String value) {
            addCriterion("TXN_CODE like", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotLike(String value) {
            addCriterion("TXN_CODE not like", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeIn(List<String> values) {
            addCriterion("TXN_CODE in", values, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotIn(List<String> values) {
            addCriterion("TXN_CODE not in", values, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeBetween(String value1, String value2) {
            addCriterion("TXN_CODE between", value1, value2, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotBetween(String value1, String value2) {
            addCriterion("TXN_CODE not between", value1, value2, "txnCode");
            return (Criteria) this;
        }

        public Criteria andSerialNoIsNull() {
            addCriterion("SERIAL_NO is null");
            return (Criteria) this;
        }

        public Criteria andSerialNoIsNotNull() {
            addCriterion("SERIAL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSerialNoEqualTo(String value) {
            addCriterion("SERIAL_NO =", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotEqualTo(String value) {
            addCriterion("SERIAL_NO <>", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoGreaterThan(String value) {
            addCriterion("SERIAL_NO >", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoGreaterThanOrEqualTo(String value) {
            addCriterion("SERIAL_NO >=", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoLessThan(String value) {
            addCriterion("SERIAL_NO <", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoLessThanOrEqualTo(String value) {
            addCriterion("SERIAL_NO <=", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoLike(String value) {
            addCriterion("SERIAL_NO like", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotLike(String value) {
            addCriterion("SERIAL_NO not like", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoIn(List<String> values) {
            addCriterion("SERIAL_NO in", values, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotIn(List<String> values) {
            addCriterion("SERIAL_NO not in", values, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoBetween(String value1, String value2) {
            addCriterion("SERIAL_NO between", value1, value2, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotBetween(String value1, String value2) {
            addCriterion("SERIAL_NO not between", value1, value2, "serialNo");
            return (Criteria) this;
        }

        public Criteria andIntNameIsNull() {
            addCriterion("INT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andIntNameIsNotNull() {
            addCriterion("INT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andIntNameEqualTo(String value) {
            addCriterion("INT_NAME =", value, "intName");
            return (Criteria) this;
        }

        public Criteria andIntNameNotEqualTo(String value) {
            addCriterion("INT_NAME <>", value, "intName");
            return (Criteria) this;
        }

        public Criteria andIntNameGreaterThan(String value) {
            addCriterion("INT_NAME >", value, "intName");
            return (Criteria) this;
        }

        public Criteria andIntNameGreaterThanOrEqualTo(String value) {
            addCriterion("INT_NAME >=", value, "intName");
            return (Criteria) this;
        }

        public Criteria andIntNameLessThan(String value) {
            addCriterion("INT_NAME <", value, "intName");
            return (Criteria) this;
        }

        public Criteria andIntNameLessThanOrEqualTo(String value) {
            addCriterion("INT_NAME <=", value, "intName");
            return (Criteria) this;
        }

        public Criteria andIntNameLike(String value) {
            addCriterion("INT_NAME like", value, "intName");
            return (Criteria) this;
        }

        public Criteria andIntNameNotLike(String value) {
            addCriterion("INT_NAME not like", value, "intName");
            return (Criteria) this;
        }

        public Criteria andIntNameIn(List<String> values) {
            addCriterion("INT_NAME in", values, "intName");
            return (Criteria) this;
        }

        public Criteria andIntNameNotIn(List<String> values) {
            addCriterion("INT_NAME not in", values, "intName");
            return (Criteria) this;
        }

        public Criteria andIntNameBetween(String value1, String value2) {
            addCriterion("INT_NAME between", value1, value2, "intName");
            return (Criteria) this;
        }

        public Criteria andIntNameNotBetween(String value1, String value2) {
            addCriterion("INT_NAME not between", value1, value2, "intName");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("DEPT_ID is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("DEPT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(String value) {
            addCriterion("DEPT_ID =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(String value) {
            addCriterion("DEPT_ID <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(String value) {
            addCriterion("DEPT_ID >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT_ID >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(String value) {
            addCriterion("DEPT_ID <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(String value) {
            addCriterion("DEPT_ID <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLike(String value) {
            addCriterion("DEPT_ID like", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotLike(String value) {
            addCriterion("DEPT_ID not like", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<String> values) {
            addCriterion("DEPT_ID in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<String> values) {
            addCriterion("DEPT_ID not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(String value1, String value2) {
            addCriterion("DEPT_ID between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(String value1, String value2) {
            addCriterion("DEPT_ID not between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andSendFlagIsNull() {
            addCriterion("SEND_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andSendFlagIsNotNull() {
            addCriterion("SEND_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andSendFlagEqualTo(String value) {
            addCriterion("SEND_FLAG =", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagNotEqualTo(String value) {
            addCriterion("SEND_FLAG <>", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagGreaterThan(String value) {
            addCriterion("SEND_FLAG >", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagGreaterThanOrEqualTo(String value) {
            addCriterion("SEND_FLAG >=", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagLessThan(String value) {
            addCriterion("SEND_FLAG <", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagLessThanOrEqualTo(String value) {
            addCriterion("SEND_FLAG <=", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagLike(String value) {
            addCriterion("SEND_FLAG like", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagNotLike(String value) {
            addCriterion("SEND_FLAG not like", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagIn(List<String> values) {
            addCriterion("SEND_FLAG in", values, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagNotIn(List<String> values) {
            addCriterion("SEND_FLAG not in", values, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagBetween(String value1, String value2) {
            addCriterion("SEND_FLAG between", value1, value2, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagNotBetween(String value1, String value2) {
            addCriterion("SEND_FLAG not between", value1, value2, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendDatetimeIsNull() {
            addCriterion("SEND_DATETIME is null");
            return (Criteria) this;
        }

        public Criteria andSendDatetimeIsNotNull() {
            addCriterion("SEND_DATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andSendDatetimeEqualTo(String value) {
            addCriterion("SEND_DATETIME =", value, "sendDatetime");
            return (Criteria) this;
        }

        public Criteria andSendDatetimeNotEqualTo(String value) {
            addCriterion("SEND_DATETIME <>", value, "sendDatetime");
            return (Criteria) this;
        }

        public Criteria andSendDatetimeGreaterThan(String value) {
            addCriterion("SEND_DATETIME >", value, "sendDatetime");
            return (Criteria) this;
        }

        public Criteria andSendDatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("SEND_DATETIME >=", value, "sendDatetime");
            return (Criteria) this;
        }

        public Criteria andSendDatetimeLessThan(String value) {
            addCriterion("SEND_DATETIME <", value, "sendDatetime");
            return (Criteria) this;
        }

        public Criteria andSendDatetimeLessThanOrEqualTo(String value) {
            addCriterion("SEND_DATETIME <=", value, "sendDatetime");
            return (Criteria) this;
        }

        public Criteria andSendDatetimeLike(String value) {
            addCriterion("SEND_DATETIME like", value, "sendDatetime");
            return (Criteria) this;
        }

        public Criteria andSendDatetimeNotLike(String value) {
            addCriterion("SEND_DATETIME not like", value, "sendDatetime");
            return (Criteria) this;
        }

        public Criteria andSendDatetimeIn(List<String> values) {
            addCriterion("SEND_DATETIME in", values, "sendDatetime");
            return (Criteria) this;
        }

        public Criteria andSendDatetimeNotIn(List<String> values) {
            addCriterion("SEND_DATETIME not in", values, "sendDatetime");
            return (Criteria) this;
        }

        public Criteria andSendDatetimeBetween(String value1, String value2) {
            addCriterion("SEND_DATETIME between", value1, value2, "sendDatetime");
            return (Criteria) this;
        }

        public Criteria andSendDatetimeNotBetween(String value1, String value2) {
            addCriterion("SEND_DATETIME not between", value1, value2, "sendDatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 22 15:31:58 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.HMFS_JM_INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}