package org.fbi.hmfsjz.repository.model;

import java.util.ArrayList;
import java.util.List;

public class HmfsJzIrtExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public HmfsJzIrtExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andCurcdeIsNull() {
            addCriterion("CURCDE is null");
            return (Criteria) this;
        }

        public Criteria andCurcdeIsNotNull() {
            addCriterion("CURCDE is not null");
            return (Criteria) this;
        }

        public Criteria andCurcdeEqualTo(String value) {
            addCriterion("CURCDE =", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotEqualTo(String value) {
            addCriterion("CURCDE <>", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeGreaterThan(String value) {
            addCriterion("CURCDE >", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeGreaterThanOrEqualTo(String value) {
            addCriterion("CURCDE >=", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLessThan(String value) {
            addCriterion("CURCDE <", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLessThanOrEqualTo(String value) {
            addCriterion("CURCDE <=", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLike(String value) {
            addCriterion("CURCDE like", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotLike(String value) {
            addCriterion("CURCDE not like", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeIn(List<String> values) {
            addCriterion("CURCDE in", values, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotIn(List<String> values) {
            addCriterion("CURCDE not in", values, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeBetween(String value1, String value2) {
            addCriterion("CURCDE between", value1, value2, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotBetween(String value1, String value2) {
            addCriterion("CURCDE not between", value1, value2, "curcde");
            return (Criteria) this;
        }

        public Criteria andIrtcodeIsNull() {
            addCriterion("IRTCODE is null");
            return (Criteria) this;
        }

        public Criteria andIrtcodeIsNotNull() {
            addCriterion("IRTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andIrtcodeEqualTo(String value) {
            addCriterion("IRTCODE =", value, "irtcode");
            return (Criteria) this;
        }

        public Criteria andIrtcodeNotEqualTo(String value) {
            addCriterion("IRTCODE <>", value, "irtcode");
            return (Criteria) this;
        }

        public Criteria andIrtcodeGreaterThan(String value) {
            addCriterion("IRTCODE >", value, "irtcode");
            return (Criteria) this;
        }

        public Criteria andIrtcodeGreaterThanOrEqualTo(String value) {
            addCriterion("IRTCODE >=", value, "irtcode");
            return (Criteria) this;
        }

        public Criteria andIrtcodeLessThan(String value) {
            addCriterion("IRTCODE <", value, "irtcode");
            return (Criteria) this;
        }

        public Criteria andIrtcodeLessThanOrEqualTo(String value) {
            addCriterion("IRTCODE <=", value, "irtcode");
            return (Criteria) this;
        }

        public Criteria andIrtcodeLike(String value) {
            addCriterion("IRTCODE like", value, "irtcode");
            return (Criteria) this;
        }

        public Criteria andIrtcodeNotLike(String value) {
            addCriterion("IRTCODE not like", value, "irtcode");
            return (Criteria) this;
        }

        public Criteria andIrtcodeIn(List<String> values) {
            addCriterion("IRTCODE in", values, "irtcode");
            return (Criteria) this;
        }

        public Criteria andIrtcodeNotIn(List<String> values) {
            addCriterion("IRTCODE not in", values, "irtcode");
            return (Criteria) this;
        }

        public Criteria andIrtcodeBetween(String value1, String value2) {
            addCriterion("IRTCODE between", value1, value2, "irtcode");
            return (Criteria) this;
        }

        public Criteria andIrtcodeNotBetween(String value1, String value2) {
            addCriterion("IRTCODE not between", value1, value2, "irtcode");
            return (Criteria) this;
        }

        public Criteria andEffdateIsNull() {
            addCriterion("EFFDATE is null");
            return (Criteria) this;
        }

        public Criteria andEffdateIsNotNull() {
            addCriterion("EFFDATE is not null");
            return (Criteria) this;
        }

        public Criteria andEffdateEqualTo(String value) {
            addCriterion("EFFDATE =", value, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateNotEqualTo(String value) {
            addCriterion("EFFDATE <>", value, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateGreaterThan(String value) {
            addCriterion("EFFDATE >", value, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateGreaterThanOrEqualTo(String value) {
            addCriterion("EFFDATE >=", value, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateLessThan(String value) {
            addCriterion("EFFDATE <", value, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateLessThanOrEqualTo(String value) {
            addCriterion("EFFDATE <=", value, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateLike(String value) {
            addCriterion("EFFDATE like", value, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateNotLike(String value) {
            addCriterion("EFFDATE not like", value, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateIn(List<String> values) {
            addCriterion("EFFDATE in", values, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateNotIn(List<String> values) {
            addCriterion("EFFDATE not in", values, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateBetween(String value1, String value2) {
            addCriterion("EFFDATE between", value1, value2, "effdate");
            return (Criteria) this;
        }

        public Criteria andEffdateNotBetween(String value1, String value2) {
            addCriterion("EFFDATE not between", value1, value2, "effdate");
            return (Criteria) this;
        }

        public Criteria andIrtvalueIsNull() {
            addCriterion("IRTVALUE is null");
            return (Criteria) this;
        }

        public Criteria andIrtvalueIsNotNull() {
            addCriterion("IRTVALUE is not null");
            return (Criteria) this;
        }

        public Criteria andIrtvalueEqualTo(String value) {
            addCriterion("IRTVALUE =", value, "irtvalue");
            return (Criteria) this;
        }

        public Criteria andIrtvalueNotEqualTo(String value) {
            addCriterion("IRTVALUE <>", value, "irtvalue");
            return (Criteria) this;
        }

        public Criteria andIrtvalueGreaterThan(String value) {
            addCriterion("IRTVALUE >", value, "irtvalue");
            return (Criteria) this;
        }

        public Criteria andIrtvalueGreaterThanOrEqualTo(String value) {
            addCriterion("IRTVALUE >=", value, "irtvalue");
            return (Criteria) this;
        }

        public Criteria andIrtvalueLessThan(String value) {
            addCriterion("IRTVALUE <", value, "irtvalue");
            return (Criteria) this;
        }

        public Criteria andIrtvalueLessThanOrEqualTo(String value) {
            addCriterion("IRTVALUE <=", value, "irtvalue");
            return (Criteria) this;
        }

        public Criteria andIrtvalueLike(String value) {
            addCriterion("IRTVALUE like", value, "irtvalue");
            return (Criteria) this;
        }

        public Criteria andIrtvalueNotLike(String value) {
            addCriterion("IRTVALUE not like", value, "irtvalue");
            return (Criteria) this;
        }

        public Criteria andIrtvalueIn(List<String> values) {
            addCriterion("IRTVALUE in", values, "irtvalue");
            return (Criteria) this;
        }

        public Criteria andIrtvalueNotIn(List<String> values) {
            addCriterion("IRTVALUE not in", values, "irtvalue");
            return (Criteria) this;
        }

        public Criteria andIrtvalueBetween(String value1, String value2) {
            addCriterion("IRTVALUE between", value1, value2, "irtvalue");
            return (Criteria) this;
        }

        public Criteria andIrtvalueNotBetween(String value1, String value2) {
            addCriterion("IRTVALUE not between", value1, value2, "irtvalue");
            return (Criteria) this;
        }

        public Criteria andCretlrIsNull() {
            addCriterion("CRETLR is null");
            return (Criteria) this;
        }

        public Criteria andCretlrIsNotNull() {
            addCriterion("CRETLR is not null");
            return (Criteria) this;
        }

        public Criteria andCretlrEqualTo(String value) {
            addCriterion("CRETLR =", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrNotEqualTo(String value) {
            addCriterion("CRETLR <>", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrGreaterThan(String value) {
            addCriterion("CRETLR >", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrGreaterThanOrEqualTo(String value) {
            addCriterion("CRETLR >=", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrLessThan(String value) {
            addCriterion("CRETLR <", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrLessThanOrEqualTo(String value) {
            addCriterion("CRETLR <=", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrLike(String value) {
            addCriterion("CRETLR like", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrNotLike(String value) {
            addCriterion("CRETLR not like", value, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrIn(List<String> values) {
            addCriterion("CRETLR in", values, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrNotIn(List<String> values) {
            addCriterion("CRETLR not in", values, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrBetween(String value1, String value2) {
            addCriterion("CRETLR between", value1, value2, "cretlr");
            return (Criteria) this;
        }

        public Criteria andCretlrNotBetween(String value1, String value2) {
            addCriterion("CRETLR not between", value1, value2, "cretlr");
            return (Criteria) this;
        }

        public Criteria andOperdateIsNull() {
            addCriterion("OPERDATE is null");
            return (Criteria) this;
        }

        public Criteria andOperdateIsNotNull() {
            addCriterion("OPERDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOperdateEqualTo(String value) {
            addCriterion("OPERDATE =", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotEqualTo(String value) {
            addCriterion("OPERDATE <>", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateGreaterThan(String value) {
            addCriterion("OPERDATE >", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateGreaterThanOrEqualTo(String value) {
            addCriterion("OPERDATE >=", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateLessThan(String value) {
            addCriterion("OPERDATE <", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateLessThanOrEqualTo(String value) {
            addCriterion("OPERDATE <=", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateLike(String value) {
            addCriterion("OPERDATE like", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotLike(String value) {
            addCriterion("OPERDATE not like", value, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateIn(List<String> values) {
            addCriterion("OPERDATE in", values, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotIn(List<String> values) {
            addCriterion("OPERDATE not in", values, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateBetween(String value1, String value2) {
            addCriterion("OPERDATE between", value1, value2, "operdate");
            return (Criteria) this;
        }

        public Criteria andOperdateNotBetween(String value1, String value2) {
            addCriterion("OPERDATE not between", value1, value2, "operdate");
            return (Criteria) this;
        }

        public Criteria andRecstsIsNull() {
            addCriterion("RECSTS is null");
            return (Criteria) this;
        }

        public Criteria andRecstsIsNotNull() {
            addCriterion("RECSTS is not null");
            return (Criteria) this;
        }

        public Criteria andRecstsEqualTo(String value) {
            addCriterion("RECSTS =", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotEqualTo(String value) {
            addCriterion("RECSTS <>", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsGreaterThan(String value) {
            addCriterion("RECSTS >", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsGreaterThanOrEqualTo(String value) {
            addCriterion("RECSTS >=", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLessThan(String value) {
            addCriterion("RECSTS <", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLessThanOrEqualTo(String value) {
            addCriterion("RECSTS <=", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLike(String value) {
            addCriterion("RECSTS like", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotLike(String value) {
            addCriterion("RECSTS not like", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsIn(List<String> values) {
            addCriterion("RECSTS in", values, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotIn(List<String> values) {
            addCriterion("RECSTS not in", values, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsBetween(String value1, String value2) {
            addCriterion("RECSTS between", value1, value2, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotBetween(String value1, String value2) {
            addCriterion("RECSTS not between", value1, value2, "recsts");
            return (Criteria) this;
        }

        public Criteria andDaysIsNull() {
            addCriterion("DAYS is null");
            return (Criteria) this;
        }

        public Criteria andDaysIsNotNull() {
            addCriterion("DAYS is not null");
            return (Criteria) this;
        }

        public Criteria andDaysEqualTo(Short value) {
            addCriterion("DAYS =", value, "days");
            return (Criteria) this;
        }

        public Criteria andDaysNotEqualTo(Short value) {
            addCriterion("DAYS <>", value, "days");
            return (Criteria) this;
        }

        public Criteria andDaysGreaterThan(Short value) {
            addCriterion("DAYS >", value, "days");
            return (Criteria) this;
        }

        public Criteria andDaysGreaterThanOrEqualTo(Short value) {
            addCriterion("DAYS >=", value, "days");
            return (Criteria) this;
        }

        public Criteria andDaysLessThan(Short value) {
            addCriterion("DAYS <", value, "days");
            return (Criteria) this;
        }

        public Criteria andDaysLessThanOrEqualTo(Short value) {
            addCriterion("DAYS <=", value, "days");
            return (Criteria) this;
        }

        public Criteria andDaysIn(List<Short> values) {
            addCriterion("DAYS in", values, "days");
            return (Criteria) this;
        }

        public Criteria andDaysNotIn(List<Short> values) {
            addCriterion("DAYS not in", values, "days");
            return (Criteria) this;
        }

        public Criteria andDaysBetween(Short value1, Short value2) {
            addCriterion("DAYS between", value1, value2, "days");
            return (Criteria) this;
        }

        public Criteria andDaysNotBetween(Short value1, Short value2) {
            addCriterion("DAYS not between", value1, value2, "days");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 22 13:20:44 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.HMFS_JZ_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}