package org.fbi.hmfsjz.repository.model;

import java.math.BigDecimal;

public class HmfsJzInterest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.PKID
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private BigDecimal interest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.INTEREST_NO
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String interestNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.HOUSE_ACCOUNT
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String houseAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.HOUSE_ID
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.HOUSE_LOCATION
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String houseLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.OWNER
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.BEFORE_AMT
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private BigDecimal beforeAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.AFTER_AMT
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private BigDecimal afterAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.BEGIN_DATE
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.END_DATE
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.CAPITAL
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private BigDecimal capital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.RATE
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.OPER_TIME
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.OPER_ID
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.REMARK
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.TXN_CODE
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String txnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.SERIAL_NO
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.INT_NAME
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String intName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.DEPT_ID
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.SEND_FLAG
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String sendFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_INTEREST.SEND_DATETIME
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    private String sendDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.PKID
     *
     * @return the value of FIS.HMFS_JM_INTEREST.PKID
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.PKID
     *
     * @param pkid the value for FIS.HMFS_JM_INTEREST.PKID
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.INTEREST
     *
     * @return the value of FIS.HMFS_JM_INTEREST.INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public BigDecimal getInterest() {
        return interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.INTEREST
     *
     * @param interest the value for FIS.HMFS_JM_INTEREST.INTEREST
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setInterest(BigDecimal interest) {
        this.interest = interest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.INTEREST_NO
     *
     * @return the value of FIS.HMFS_JM_INTEREST.INTEREST_NO
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getInterestNo() {
        return interestNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.INTEREST_NO
     *
     * @param interestNo the value for FIS.HMFS_JM_INTEREST.INTEREST_NO
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setInterestNo(String interestNo) {
        this.interestNo = interestNo == null ? null : interestNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.HOUSE_ACCOUNT
     *
     * @return the value of FIS.HMFS_JM_INTEREST.HOUSE_ACCOUNT
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getHouseAccount() {
        return houseAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.HOUSE_ACCOUNT
     *
     * @param houseAccount the value for FIS.HMFS_JM_INTEREST.HOUSE_ACCOUNT
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setHouseAccount(String houseAccount) {
        this.houseAccount = houseAccount == null ? null : houseAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.HOUSE_ID
     *
     * @return the value of FIS.HMFS_JM_INTEREST.HOUSE_ID
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.HOUSE_ID
     *
     * @param houseId the value for FIS.HMFS_JM_INTEREST.HOUSE_ID
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setHouseId(String houseId) {
        this.houseId = houseId == null ? null : houseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.HOUSE_LOCATION
     *
     * @return the value of FIS.HMFS_JM_INTEREST.HOUSE_LOCATION
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getHouseLocation() {
        return houseLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.HOUSE_LOCATION
     *
     * @param houseLocation the value for FIS.HMFS_JM_INTEREST.HOUSE_LOCATION
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setHouseLocation(String houseLocation) {
        this.houseLocation = houseLocation == null ? null : houseLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.OWNER
     *
     * @return the value of FIS.HMFS_JM_INTEREST.OWNER
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.OWNER
     *
     * @param owner the value for FIS.HMFS_JM_INTEREST.OWNER
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.BEFORE_AMT
     *
     * @return the value of FIS.HMFS_JM_INTEREST.BEFORE_AMT
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public BigDecimal getBeforeAmt() {
        return beforeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.BEFORE_AMT
     *
     * @param beforeAmt the value for FIS.HMFS_JM_INTEREST.BEFORE_AMT
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setBeforeAmt(BigDecimal beforeAmt) {
        this.beforeAmt = beforeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.AFTER_AMT
     *
     * @return the value of FIS.HMFS_JM_INTEREST.AFTER_AMT
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public BigDecimal getAfterAmt() {
        return afterAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.AFTER_AMT
     *
     * @param afterAmt the value for FIS.HMFS_JM_INTEREST.AFTER_AMT
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setAfterAmt(BigDecimal afterAmt) {
        this.afterAmt = afterAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.BEGIN_DATE
     *
     * @return the value of FIS.HMFS_JM_INTEREST.BEGIN_DATE
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.BEGIN_DATE
     *
     * @param beginDate the value for FIS.HMFS_JM_INTEREST.BEGIN_DATE
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setBeginDate(String beginDate) {
        this.beginDate = beginDate == null ? null : beginDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.END_DATE
     *
     * @return the value of FIS.HMFS_JM_INTEREST.END_DATE
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.END_DATE
     *
     * @param endDate the value for FIS.HMFS_JM_INTEREST.END_DATE
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.CAPITAL
     *
     * @return the value of FIS.HMFS_JM_INTEREST.CAPITAL
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public BigDecimal getCapital() {
        return capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.CAPITAL
     *
     * @param capital the value for FIS.HMFS_JM_INTEREST.CAPITAL
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setCapital(BigDecimal capital) {
        this.capital = capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.RATE
     *
     * @return the value of FIS.HMFS_JM_INTEREST.RATE
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.RATE
     *
     * @param rate the value for FIS.HMFS_JM_INTEREST.RATE
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setRate(String rate) {
        this.rate = rate == null ? null : rate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.OPER_TIME
     *
     * @return the value of FIS.HMFS_JM_INTEREST.OPER_TIME
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.OPER_TIME
     *
     * @param operTime the value for FIS.HMFS_JM_INTEREST.OPER_TIME
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime == null ? null : operTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.OPER_ID
     *
     * @return the value of FIS.HMFS_JM_INTEREST.OPER_ID
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.OPER_ID
     *
     * @param operId the value for FIS.HMFS_JM_INTEREST.OPER_ID
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.REMARK
     *
     * @return the value of FIS.HMFS_JM_INTEREST.REMARK
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.REMARK
     *
     * @param remark the value for FIS.HMFS_JM_INTEREST.REMARK
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.TXN_CODE
     *
     * @return the value of FIS.HMFS_JM_INTEREST.TXN_CODE
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getTxnCode() {
        return txnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.TXN_CODE
     *
     * @param txnCode the value for FIS.HMFS_JM_INTEREST.TXN_CODE
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setTxnCode(String txnCode) {
        this.txnCode = txnCode == null ? null : txnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.SERIAL_NO
     *
     * @return the value of FIS.HMFS_JM_INTEREST.SERIAL_NO
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.SERIAL_NO
     *
     * @param serialNo the value for FIS.HMFS_JM_INTEREST.SERIAL_NO
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.INT_NAME
     *
     * @return the value of FIS.HMFS_JM_INTEREST.INT_NAME
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getIntName() {
        return intName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.INT_NAME
     *
     * @param intName the value for FIS.HMFS_JM_INTEREST.INT_NAME
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setIntName(String intName) {
        this.intName = intName == null ? null : intName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.DEPT_ID
     *
     * @return the value of FIS.HMFS_JM_INTEREST.DEPT_ID
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.DEPT_ID
     *
     * @param deptId the value for FIS.HMFS_JM_INTEREST.DEPT_ID
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.SEND_FLAG
     *
     * @return the value of FIS.HMFS_JM_INTEREST.SEND_FLAG
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getSendFlag() {
        return sendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.SEND_FLAG
     *
     * @param sendFlag the value for FIS.HMFS_JM_INTEREST.SEND_FLAG
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setSendFlag(String sendFlag) {
        this.sendFlag = sendFlag == null ? null : sendFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_INTEREST.SEND_DATETIME
     *
     * @return the value of FIS.HMFS_JM_INTEREST.SEND_DATETIME
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public String getSendDatetime() {
        return sendDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_INTEREST.SEND_DATETIME
     *
     * @param sendDatetime the value for FIS.HMFS_JM_INTEREST.SEND_DATETIME
     *
     * @mbggenerated Wed Oct 22 15:31:58 CST 2014
     */
    public void setSendDatetime(String sendDatetime) {
        this.sendDatetime = sendDatetime == null ? null : sendDatetime.trim();
    }
}