package org.fbi.hmfsjz.repository.model;

import java.math.BigDecimal;

public class HmfsJzBill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.PKID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.BILLNO
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.BILL_STS_CODE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String billStsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.BILL_STS_TITLE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String billStsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.HOUSE_ID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.HOUSE_LOCATION
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String houseLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.HOUSE_AREA
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String houseArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.STANDARD
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String standard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.TXN_AMT
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private BigDecimal txnAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.PAY_BANK
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String payBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.AREA_ACCOUNT
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String areaAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.HOUSE_ACCOUNT
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String houseAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.CARD_TYPE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.CARD_NO
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.OWNER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.TEL
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.RESERVE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String reserve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.OPER_DATE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.OPER_TIME
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.OPER_ID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.REMARK
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.CFM_TXN_CODE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String cfmTxnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.QRY_TXN_CODE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String qryTxnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.ACT_SERIAL_NO
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String actSerialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.BOOK_TYPE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String bookType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.STS_FLAG
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String stsFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.RELATE_BILLNO
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String relateBillno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_BILL.DEPT_ID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.PKID
     *
     * @return the value of FIS.HMFS_JM_BILL.PKID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.PKID
     *
     * @param pkid the value for FIS.HMFS_JM_BILL.PKID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.BILLNO
     *
     * @return the value of FIS.HMFS_JM_BILL.BILLNO
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.BILLNO
     *
     * @param billno the value for FIS.HMFS_JM_BILL.BILLNO
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.BILL_STS_CODE
     *
     * @return the value of FIS.HMFS_JM_BILL.BILL_STS_CODE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getBillStsCode() {
        return billStsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.BILL_STS_CODE
     *
     * @param billStsCode the value for FIS.HMFS_JM_BILL.BILL_STS_CODE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setBillStsCode(String billStsCode) {
        this.billStsCode = billStsCode == null ? null : billStsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.BILL_STS_TITLE
     *
     * @return the value of FIS.HMFS_JM_BILL.BILL_STS_TITLE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getBillStsTitle() {
        return billStsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.BILL_STS_TITLE
     *
     * @param billStsTitle the value for FIS.HMFS_JM_BILL.BILL_STS_TITLE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setBillStsTitle(String billStsTitle) {
        this.billStsTitle = billStsTitle == null ? null : billStsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.HOUSE_ID
     *
     * @return the value of FIS.HMFS_JM_BILL.HOUSE_ID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.HOUSE_ID
     *
     * @param houseId the value for FIS.HMFS_JM_BILL.HOUSE_ID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setHouseId(String houseId) {
        this.houseId = houseId == null ? null : houseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.HOUSE_LOCATION
     *
     * @return the value of FIS.HMFS_JM_BILL.HOUSE_LOCATION
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getHouseLocation() {
        return houseLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.HOUSE_LOCATION
     *
     * @param houseLocation the value for FIS.HMFS_JM_BILL.HOUSE_LOCATION
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setHouseLocation(String houseLocation) {
        this.houseLocation = houseLocation == null ? null : houseLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.HOUSE_AREA
     *
     * @return the value of FIS.HMFS_JM_BILL.HOUSE_AREA
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getHouseArea() {
        return houseArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.HOUSE_AREA
     *
     * @param houseArea the value for FIS.HMFS_JM_BILL.HOUSE_AREA
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setHouseArea(String houseArea) {
        this.houseArea = houseArea == null ? null : houseArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.STANDARD
     *
     * @return the value of FIS.HMFS_JM_BILL.STANDARD
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.STANDARD
     *
     * @param standard the value for FIS.HMFS_JM_BILL.STANDARD
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.TXN_AMT
     *
     * @return the value of FIS.HMFS_JM_BILL.TXN_AMT
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public BigDecimal getTxnAmt() {
        return txnAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.TXN_AMT
     *
     * @param txnAmt the value for FIS.HMFS_JM_BILL.TXN_AMT
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setTxnAmt(BigDecimal txnAmt) {
        this.txnAmt = txnAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.PAY_BANK
     *
     * @return the value of FIS.HMFS_JM_BILL.PAY_BANK
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getPayBank() {
        return payBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.PAY_BANK
     *
     * @param payBank the value for FIS.HMFS_JM_BILL.PAY_BANK
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setPayBank(String payBank) {
        this.payBank = payBank == null ? null : payBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.AREA_ACCOUNT
     *
     * @return the value of FIS.HMFS_JM_BILL.AREA_ACCOUNT
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getAreaAccount() {
        return areaAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.AREA_ACCOUNT
     *
     * @param areaAccount the value for FIS.HMFS_JM_BILL.AREA_ACCOUNT
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setAreaAccount(String areaAccount) {
        this.areaAccount = areaAccount == null ? null : areaAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.HOUSE_ACCOUNT
     *
     * @return the value of FIS.HMFS_JM_BILL.HOUSE_ACCOUNT
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getHouseAccount() {
        return houseAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.HOUSE_ACCOUNT
     *
     * @param houseAccount the value for FIS.HMFS_JM_BILL.HOUSE_ACCOUNT
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setHouseAccount(String houseAccount) {
        this.houseAccount = houseAccount == null ? null : houseAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.CARD_TYPE
     *
     * @return the value of FIS.HMFS_JM_BILL.CARD_TYPE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.CARD_TYPE
     *
     * @param cardType the value for FIS.HMFS_JM_BILL.CARD_TYPE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.CARD_NO
     *
     * @return the value of FIS.HMFS_JM_BILL.CARD_NO
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.CARD_NO
     *
     * @param cardNo the value for FIS.HMFS_JM_BILL.CARD_NO
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.OWNER
     *
     * @return the value of FIS.HMFS_JM_BILL.OWNER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.OWNER
     *
     * @param owner the value for FIS.HMFS_JM_BILL.OWNER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.TEL
     *
     * @return the value of FIS.HMFS_JM_BILL.TEL
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.TEL
     *
     * @param tel the value for FIS.HMFS_JM_BILL.TEL
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.RESERVE
     *
     * @return the value of FIS.HMFS_JM_BILL.RESERVE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getReserve() {
        return reserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.RESERVE
     *
     * @param reserve the value for FIS.HMFS_JM_BILL.RESERVE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setReserve(String reserve) {
        this.reserve = reserve == null ? null : reserve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.OPER_DATE
     *
     * @return the value of FIS.HMFS_JM_BILL.OPER_DATE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.OPER_DATE
     *
     * @param operDate the value for FIS.HMFS_JM_BILL.OPER_DATE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.OPER_TIME
     *
     * @return the value of FIS.HMFS_JM_BILL.OPER_TIME
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.OPER_TIME
     *
     * @param operTime the value for FIS.HMFS_JM_BILL.OPER_TIME
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime == null ? null : operTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.OPER_ID
     *
     * @return the value of FIS.HMFS_JM_BILL.OPER_ID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.OPER_ID
     *
     * @param operId the value for FIS.HMFS_JM_BILL.OPER_ID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.REMARK
     *
     * @return the value of FIS.HMFS_JM_BILL.REMARK
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.REMARK
     *
     * @param remark the value for FIS.HMFS_JM_BILL.REMARK
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.CFM_TXN_CODE
     *
     * @return the value of FIS.HMFS_JM_BILL.CFM_TXN_CODE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getCfmTxnCode() {
        return cfmTxnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.CFM_TXN_CODE
     *
     * @param cfmTxnCode the value for FIS.HMFS_JM_BILL.CFM_TXN_CODE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setCfmTxnCode(String cfmTxnCode) {
        this.cfmTxnCode = cfmTxnCode == null ? null : cfmTxnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.QRY_TXN_CODE
     *
     * @return the value of FIS.HMFS_JM_BILL.QRY_TXN_CODE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getQryTxnCode() {
        return qryTxnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.QRY_TXN_CODE
     *
     * @param qryTxnCode the value for FIS.HMFS_JM_BILL.QRY_TXN_CODE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setQryTxnCode(String qryTxnCode) {
        this.qryTxnCode = qryTxnCode == null ? null : qryTxnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.ACT_SERIAL_NO
     *
     * @return the value of FIS.HMFS_JM_BILL.ACT_SERIAL_NO
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getActSerialNo() {
        return actSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.ACT_SERIAL_NO
     *
     * @param actSerialNo the value for FIS.HMFS_JM_BILL.ACT_SERIAL_NO
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setActSerialNo(String actSerialNo) {
        this.actSerialNo = actSerialNo == null ? null : actSerialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.BOOK_TYPE
     *
     * @return the value of FIS.HMFS_JM_BILL.BOOK_TYPE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getBookType() {
        return bookType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.BOOK_TYPE
     *
     * @param bookType the value for FIS.HMFS_JM_BILL.BOOK_TYPE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setBookType(String bookType) {
        this.bookType = bookType == null ? null : bookType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.STS_FLAG
     *
     * @return the value of FIS.HMFS_JM_BILL.STS_FLAG
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getStsFlag() {
        return stsFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.STS_FLAG
     *
     * @param stsFlag the value for FIS.HMFS_JM_BILL.STS_FLAG
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setStsFlag(String stsFlag) {
        this.stsFlag = stsFlag == null ? null : stsFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.RELATE_BILLNO
     *
     * @return the value of FIS.HMFS_JM_BILL.RELATE_BILLNO
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getRelateBillno() {
        return relateBillno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.RELATE_BILLNO
     *
     * @param relateBillno the value for FIS.HMFS_JM_BILL.RELATE_BILLNO
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setRelateBillno(String relateBillno) {
        this.relateBillno = relateBillno == null ? null : relateBillno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_BILL.DEPT_ID
     *
     * @return the value of FIS.HMFS_JM_BILL.DEPT_ID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_BILL.DEPT_ID
     *
     * @param deptId the value for FIS.HMFS_JM_BILL.DEPT_ID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }
}