package org.fbi.hmfsjz.repository.model;

import java.util.ArrayList;
import java.util.List;

public class HmfsJzVoucherExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public HmfsJzVoucherExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andBillnoIsNull() {
            addCriterion("BILLNO is null");
            return (Criteria) this;
        }

        public Criteria andBillnoIsNotNull() {
            addCriterion("BILLNO is not null");
            return (Criteria) this;
        }

        public Criteria andBillnoEqualTo(String value) {
            addCriterion("BILLNO =", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoNotEqualTo(String value) {
            addCriterion("BILLNO <>", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoGreaterThan(String value) {
            addCriterion("BILLNO >", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoGreaterThanOrEqualTo(String value) {
            addCriterion("BILLNO >=", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoLessThan(String value) {
            addCriterion("BILLNO <", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoLessThanOrEqualTo(String value) {
            addCriterion("BILLNO <=", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoLike(String value) {
            addCriterion("BILLNO like", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoNotLike(String value) {
            addCriterion("BILLNO not like", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoIn(List<String> values) {
            addCriterion("BILLNO in", values, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoNotIn(List<String> values) {
            addCriterion("BILLNO not in", values, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoBetween(String value1, String value2) {
            addCriterion("BILLNO between", value1, value2, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoNotBetween(String value1, String value2) {
            addCriterion("BILLNO not between", value1, value2, "billno");
            return (Criteria) this;
        }

        public Criteria andTxnDateIsNull() {
            addCriterion("TXN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTxnDateIsNotNull() {
            addCriterion("TXN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnDateEqualTo(String value) {
            addCriterion("TXN_DATE =", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotEqualTo(String value) {
            addCriterion("TXN_DATE <>", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateGreaterThan(String value) {
            addCriterion("TXN_DATE >", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_DATE >=", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLessThan(String value) {
            addCriterion("TXN_DATE <", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLessThanOrEqualTo(String value) {
            addCriterion("TXN_DATE <=", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLike(String value) {
            addCriterion("TXN_DATE like", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotLike(String value) {
            addCriterion("TXN_DATE not like", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateIn(List<String> values) {
            addCriterion("TXN_DATE in", values, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotIn(List<String> values) {
            addCriterion("TXN_DATE not in", values, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateBetween(String value1, String value2) {
            addCriterion("TXN_DATE between", value1, value2, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotBetween(String value1, String value2) {
            addCriterion("TXN_DATE not between", value1, value2, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnCodeIsNull() {
            addCriterion("TXN_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTxnCodeIsNotNull() {
            addCriterion("TXN_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnCodeEqualTo(String value) {
            addCriterion("TXN_CODE =", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotEqualTo(String value) {
            addCriterion("TXN_CODE <>", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeGreaterThan(String value) {
            addCriterion("TXN_CODE >", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_CODE >=", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeLessThan(String value) {
            addCriterion("TXN_CODE <", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeLessThanOrEqualTo(String value) {
            addCriterion("TXN_CODE <=", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeLike(String value) {
            addCriterion("TXN_CODE like", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotLike(String value) {
            addCriterion("TXN_CODE not like", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeIn(List<String> values) {
            addCriterion("TXN_CODE in", values, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotIn(List<String> values) {
            addCriterion("TXN_CODE not in", values, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeBetween(String value1, String value2) {
            addCriterion("TXN_CODE between", value1, value2, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotBetween(String value1, String value2) {
            addCriterion("TXN_CODE not between", value1, value2, "txnCode");
            return (Criteria) this;
        }

        public Criteria andVchStsIsNull() {
            addCriterion("VCH_STS is null");
            return (Criteria) this;
        }

        public Criteria andVchStsIsNotNull() {
            addCriterion("VCH_STS is not null");
            return (Criteria) this;
        }

        public Criteria andVchStsEqualTo(String value) {
            addCriterion("VCH_STS =", value, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsNotEqualTo(String value) {
            addCriterion("VCH_STS <>", value, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsGreaterThan(String value) {
            addCriterion("VCH_STS >", value, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsGreaterThanOrEqualTo(String value) {
            addCriterion("VCH_STS >=", value, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsLessThan(String value) {
            addCriterion("VCH_STS <", value, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsLessThanOrEqualTo(String value) {
            addCriterion("VCH_STS <=", value, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsLike(String value) {
            addCriterion("VCH_STS like", value, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsNotLike(String value) {
            addCriterion("VCH_STS not like", value, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsIn(List<String> values) {
            addCriterion("VCH_STS in", values, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsNotIn(List<String> values) {
            addCriterion("VCH_STS not in", values, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsBetween(String value1, String value2) {
            addCriterion("VCH_STS between", value1, value2, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsNotBetween(String value1, String value2) {
            addCriterion("VCH_STS not between", value1, value2, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchTypeIsNull() {
            addCriterion("VCH_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andVchTypeIsNotNull() {
            addCriterion("VCH_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andVchTypeEqualTo(String value) {
            addCriterion("VCH_TYPE =", value, "vchType");
            return (Criteria) this;
        }

        public Criteria andVchTypeNotEqualTo(String value) {
            addCriterion("VCH_TYPE <>", value, "vchType");
            return (Criteria) this;
        }

        public Criteria andVchTypeGreaterThan(String value) {
            addCriterion("VCH_TYPE >", value, "vchType");
            return (Criteria) this;
        }

        public Criteria andVchTypeGreaterThanOrEqualTo(String value) {
            addCriterion("VCH_TYPE >=", value, "vchType");
            return (Criteria) this;
        }

        public Criteria andVchTypeLessThan(String value) {
            addCriterion("VCH_TYPE <", value, "vchType");
            return (Criteria) this;
        }

        public Criteria andVchTypeLessThanOrEqualTo(String value) {
            addCriterion("VCH_TYPE <=", value, "vchType");
            return (Criteria) this;
        }

        public Criteria andVchTypeLike(String value) {
            addCriterion("VCH_TYPE like", value, "vchType");
            return (Criteria) this;
        }

        public Criteria andVchTypeNotLike(String value) {
            addCriterion("VCH_TYPE not like", value, "vchType");
            return (Criteria) this;
        }

        public Criteria andVchTypeIn(List<String> values) {
            addCriterion("VCH_TYPE in", values, "vchType");
            return (Criteria) this;
        }

        public Criteria andVchTypeNotIn(List<String> values) {
            addCriterion("VCH_TYPE not in", values, "vchType");
            return (Criteria) this;
        }

        public Criteria andVchTypeBetween(String value1, String value2) {
            addCriterion("VCH_TYPE between", value1, value2, "vchType");
            return (Criteria) this;
        }

        public Criteria andVchTypeNotBetween(String value1, String value2) {
            addCriterion("VCH_TYPE not between", value1, value2, "vchType");
            return (Criteria) this;
        }

        public Criteria andVchNumIsNull() {
            addCriterion("VCH_NUM is null");
            return (Criteria) this;
        }

        public Criteria andVchNumIsNotNull() {
            addCriterion("VCH_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andVchNumEqualTo(String value) {
            addCriterion("VCH_NUM =", value, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumNotEqualTo(String value) {
            addCriterion("VCH_NUM <>", value, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumGreaterThan(String value) {
            addCriterion("VCH_NUM >", value, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumGreaterThanOrEqualTo(String value) {
            addCriterion("VCH_NUM >=", value, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumLessThan(String value) {
            addCriterion("VCH_NUM <", value, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumLessThanOrEqualTo(String value) {
            addCriterion("VCH_NUM <=", value, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumLike(String value) {
            addCriterion("VCH_NUM like", value, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumNotLike(String value) {
            addCriterion("VCH_NUM not like", value, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumIn(List<String> values) {
            addCriterion("VCH_NUM in", values, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumNotIn(List<String> values) {
            addCriterion("VCH_NUM not in", values, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumBetween(String value1, String value2) {
            addCriterion("VCH_NUM between", value1, value2, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumNotBetween(String value1, String value2) {
            addCriterion("VCH_NUM not between", value1, value2, "vchNum");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNull() {
            addCriterion("OPER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNotNull() {
            addCriterion("OPER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOperIdEqualTo(String value) {
            addCriterion("OPER_ID =", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotEqualTo(String value) {
            addCriterion("OPER_ID <>", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThan(String value) {
            addCriterion("OPER_ID >", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_ID >=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThan(String value) {
            addCriterion("OPER_ID <", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThanOrEqualTo(String value) {
            addCriterion("OPER_ID <=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLike(String value) {
            addCriterion("OPER_ID like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotLike(String value) {
            addCriterion("OPER_ID not like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdIn(List<String> values) {
            addCriterion("OPER_ID in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotIn(List<String> values) {
            addCriterion("OPER_ID not in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdBetween(String value1, String value2) {
            addCriterion("OPER_ID between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotBetween(String value1, String value2) {
            addCriterion("OPER_ID not between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andActTxnSnIsNull() {
            addCriterion("ACT_TXN_SN is null");
            return (Criteria) this;
        }

        public Criteria andActTxnSnIsNotNull() {
            addCriterion("ACT_TXN_SN is not null");
            return (Criteria) this;
        }

        public Criteria andActTxnSnEqualTo(String value) {
            addCriterion("ACT_TXN_SN =", value, "actTxnSn");
            return (Criteria) this;
        }

        public Criteria andActTxnSnNotEqualTo(String value) {
            addCriterion("ACT_TXN_SN <>", value, "actTxnSn");
            return (Criteria) this;
        }

        public Criteria andActTxnSnGreaterThan(String value) {
            addCriterion("ACT_TXN_SN >", value, "actTxnSn");
            return (Criteria) this;
        }

        public Criteria andActTxnSnGreaterThanOrEqualTo(String value) {
            addCriterion("ACT_TXN_SN >=", value, "actTxnSn");
            return (Criteria) this;
        }

        public Criteria andActTxnSnLessThan(String value) {
            addCriterion("ACT_TXN_SN <", value, "actTxnSn");
            return (Criteria) this;
        }

        public Criteria andActTxnSnLessThanOrEqualTo(String value) {
            addCriterion("ACT_TXN_SN <=", value, "actTxnSn");
            return (Criteria) this;
        }

        public Criteria andActTxnSnLike(String value) {
            addCriterion("ACT_TXN_SN like", value, "actTxnSn");
            return (Criteria) this;
        }

        public Criteria andActTxnSnNotLike(String value) {
            addCriterion("ACT_TXN_SN not like", value, "actTxnSn");
            return (Criteria) this;
        }

        public Criteria andActTxnSnIn(List<String> values) {
            addCriterion("ACT_TXN_SN in", values, "actTxnSn");
            return (Criteria) this;
        }

        public Criteria andActTxnSnNotIn(List<String> values) {
            addCriterion("ACT_TXN_SN not in", values, "actTxnSn");
            return (Criteria) this;
        }

        public Criteria andActTxnSnBetween(String value1, String value2) {
            addCriterion("ACT_TXN_SN between", value1, value2, "actTxnSn");
            return (Criteria) this;
        }

        public Criteria andActTxnSnNotBetween(String value1, String value2) {
            addCriterion("ACT_TXN_SN not between", value1, value2, "actTxnSn");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("DEPT_ID is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("DEPT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(String value) {
            addCriterion("DEPT_ID =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(String value) {
            addCriterion("DEPT_ID <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(String value) {
            addCriterion("DEPT_ID >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT_ID >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(String value) {
            addCriterion("DEPT_ID <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(String value) {
            addCriterion("DEPT_ID <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLike(String value) {
            addCriterion("DEPT_ID like", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotLike(String value) {
            addCriterion("DEPT_ID not like", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<String> values) {
            addCriterion("DEPT_ID in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<String> values) {
            addCriterion("DEPT_ID not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(String value1, String value2) {
            addCriterion("DEPT_ID between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(String value1, String value2) {
            addCriterion("DEPT_ID not between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andSendFlagIsNull() {
            addCriterion("SEND_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andSendFlagIsNotNull() {
            addCriterion("SEND_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andSendFlagEqualTo(String value) {
            addCriterion("SEND_FLAG =", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagNotEqualTo(String value) {
            addCriterion("SEND_FLAG <>", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagGreaterThan(String value) {
            addCriterion("SEND_FLAG >", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagGreaterThanOrEqualTo(String value) {
            addCriterion("SEND_FLAG >=", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagLessThan(String value) {
            addCriterion("SEND_FLAG <", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagLessThanOrEqualTo(String value) {
            addCriterion("SEND_FLAG <=", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagLike(String value) {
            addCriterion("SEND_FLAG like", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagNotLike(String value) {
            addCriterion("SEND_FLAG not like", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagIn(List<String> values) {
            addCriterion("SEND_FLAG in", values, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagNotIn(List<String> values) {
            addCriterion("SEND_FLAG not in", values, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagBetween(String value1, String value2) {
            addCriterion("SEND_FLAG between", value1, value2, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagNotBetween(String value1, String value2) {
            addCriterion("SEND_FLAG not between", value1, value2, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andTxnTimeIsNull() {
            addCriterion("TXN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andTxnTimeIsNotNull() {
            addCriterion("TXN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTxnTimeEqualTo(String value) {
            addCriterion("TXN_TIME =", value, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeNotEqualTo(String value) {
            addCriterion("TXN_TIME <>", value, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeGreaterThan(String value) {
            addCriterion("TXN_TIME >", value, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_TIME >=", value, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeLessThan(String value) {
            addCriterion("TXN_TIME <", value, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeLessThanOrEqualTo(String value) {
            addCriterion("TXN_TIME <=", value, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeLike(String value) {
            addCriterion("TXN_TIME like", value, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeNotLike(String value) {
            addCriterion("TXN_TIME not like", value, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeIn(List<String> values) {
            addCriterion("TXN_TIME in", values, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeNotIn(List<String> values) {
            addCriterion("TXN_TIME not in", values, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeBetween(String value1, String value2) {
            addCriterion("TXN_TIME between", value1, value2, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeNotBetween(String value1, String value2) {
            addCriterion("TXN_TIME not between", value1, value2, "txnTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 06 15:07:04 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.HMFS_JM_VOUCHER
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}