package org.fbi.hmfsjz.repository.model;

import java.math.BigDecimal;

public class HmfsJzAct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.PKID
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.HOUSE_ID
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String houseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.HOUSE_LOCATION
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String houseLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.HOUSE_AREA
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String houseArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.STANDARD
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String standard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.BAL_AMT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private BigDecimal balAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.AREA_ACCOUNT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String areaAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.HOUSE_ACCOUNT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String houseAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.CARD_TYPE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.CARD_NO
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.OWNER
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.TEL
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.RESERVE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String reserve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.OPER_DATE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.OPER_TIME
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.OPER_ID
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.REMARK
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.INT_AMT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private BigDecimal intAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.MNG_AMT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private BigDecimal mngAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.DEPT_ID
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.LAST_DEP_DATE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String lastDepDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.INT_DATE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String intDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.FIRST_DATE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String firstDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.FIRST_AMT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private BigDecimal firstAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_ACT.ACT_STATUS
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    private String actStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.PKID
     *
     * @return the value of FIS.HMFS_JM_ACT.PKID
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.PKID
     *
     * @param pkid the value for FIS.HMFS_JM_ACT.PKID
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.HOUSE_ID
     *
     * @return the value of FIS.HMFS_JM_ACT.HOUSE_ID
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getHouseId() {
        return houseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.HOUSE_ID
     *
     * @param houseId the value for FIS.HMFS_JM_ACT.HOUSE_ID
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setHouseId(String houseId) {
        this.houseId = houseId == null ? null : houseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.HOUSE_LOCATION
     *
     * @return the value of FIS.HMFS_JM_ACT.HOUSE_LOCATION
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getHouseLocation() {
        return houseLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.HOUSE_LOCATION
     *
     * @param houseLocation the value for FIS.HMFS_JM_ACT.HOUSE_LOCATION
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setHouseLocation(String houseLocation) {
        this.houseLocation = houseLocation == null ? null : houseLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.HOUSE_AREA
     *
     * @return the value of FIS.HMFS_JM_ACT.HOUSE_AREA
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getHouseArea() {
        return houseArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.HOUSE_AREA
     *
     * @param houseArea the value for FIS.HMFS_JM_ACT.HOUSE_AREA
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setHouseArea(String houseArea) {
        this.houseArea = houseArea == null ? null : houseArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.STANDARD
     *
     * @return the value of FIS.HMFS_JM_ACT.STANDARD
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.STANDARD
     *
     * @param standard the value for FIS.HMFS_JM_ACT.STANDARD
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setStandard(String standard) {
        this.standard = standard == null ? null : standard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.BAL_AMT
     *
     * @return the value of FIS.HMFS_JM_ACT.BAL_AMT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public BigDecimal getBalAmt() {
        return balAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.BAL_AMT
     *
     * @param balAmt the value for FIS.HMFS_JM_ACT.BAL_AMT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setBalAmt(BigDecimal balAmt) {
        this.balAmt = balAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.AREA_ACCOUNT
     *
     * @return the value of FIS.HMFS_JM_ACT.AREA_ACCOUNT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getAreaAccount() {
        return areaAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.AREA_ACCOUNT
     *
     * @param areaAccount the value for FIS.HMFS_JM_ACT.AREA_ACCOUNT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setAreaAccount(String areaAccount) {
        this.areaAccount = areaAccount == null ? null : areaAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.HOUSE_ACCOUNT
     *
     * @return the value of FIS.HMFS_JM_ACT.HOUSE_ACCOUNT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getHouseAccount() {
        return houseAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.HOUSE_ACCOUNT
     *
     * @param houseAccount the value for FIS.HMFS_JM_ACT.HOUSE_ACCOUNT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setHouseAccount(String houseAccount) {
        this.houseAccount = houseAccount == null ? null : houseAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.CARD_TYPE
     *
     * @return the value of FIS.HMFS_JM_ACT.CARD_TYPE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.CARD_TYPE
     *
     * @param cardType the value for FIS.HMFS_JM_ACT.CARD_TYPE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.CARD_NO
     *
     * @return the value of FIS.HMFS_JM_ACT.CARD_NO
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.CARD_NO
     *
     * @param cardNo the value for FIS.HMFS_JM_ACT.CARD_NO
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.OWNER
     *
     * @return the value of FIS.HMFS_JM_ACT.OWNER
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.OWNER
     *
     * @param owner the value for FIS.HMFS_JM_ACT.OWNER
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.TEL
     *
     * @return the value of FIS.HMFS_JM_ACT.TEL
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.TEL
     *
     * @param tel the value for FIS.HMFS_JM_ACT.TEL
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.RESERVE
     *
     * @return the value of FIS.HMFS_JM_ACT.RESERVE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getReserve() {
        return reserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.RESERVE
     *
     * @param reserve the value for FIS.HMFS_JM_ACT.RESERVE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setReserve(String reserve) {
        this.reserve = reserve == null ? null : reserve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.OPER_DATE
     *
     * @return the value of FIS.HMFS_JM_ACT.OPER_DATE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.OPER_DATE
     *
     * @param operDate the value for FIS.HMFS_JM_ACT.OPER_DATE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.OPER_TIME
     *
     * @return the value of FIS.HMFS_JM_ACT.OPER_TIME
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.OPER_TIME
     *
     * @param operTime the value for FIS.HMFS_JM_ACT.OPER_TIME
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime == null ? null : operTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.OPER_ID
     *
     * @return the value of FIS.HMFS_JM_ACT.OPER_ID
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.OPER_ID
     *
     * @param operId the value for FIS.HMFS_JM_ACT.OPER_ID
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.REMARK
     *
     * @return the value of FIS.HMFS_JM_ACT.REMARK
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.REMARK
     *
     * @param remark the value for FIS.HMFS_JM_ACT.REMARK
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.INT_AMT
     *
     * @return the value of FIS.HMFS_JM_ACT.INT_AMT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public BigDecimal getIntAmt() {
        return intAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.INT_AMT
     *
     * @param intAmt the value for FIS.HMFS_JM_ACT.INT_AMT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setIntAmt(BigDecimal intAmt) {
        this.intAmt = intAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.MNG_AMT
     *
     * @return the value of FIS.HMFS_JM_ACT.MNG_AMT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public BigDecimal getMngAmt() {
        return mngAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.MNG_AMT
     *
     * @param mngAmt the value for FIS.HMFS_JM_ACT.MNG_AMT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setMngAmt(BigDecimal mngAmt) {
        this.mngAmt = mngAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.DEPT_ID
     *
     * @return the value of FIS.HMFS_JM_ACT.DEPT_ID
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.DEPT_ID
     *
     * @param deptId the value for FIS.HMFS_JM_ACT.DEPT_ID
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.LAST_DEP_DATE
     *
     * @return the value of FIS.HMFS_JM_ACT.LAST_DEP_DATE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getLastDepDate() {
        return lastDepDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.LAST_DEP_DATE
     *
     * @param lastDepDate the value for FIS.HMFS_JM_ACT.LAST_DEP_DATE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setLastDepDate(String lastDepDate) {
        this.lastDepDate = lastDepDate == null ? null : lastDepDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.INT_DATE
     *
     * @return the value of FIS.HMFS_JM_ACT.INT_DATE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getIntDate() {
        return intDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.INT_DATE
     *
     * @param intDate the value for FIS.HMFS_JM_ACT.INT_DATE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setIntDate(String intDate) {
        this.intDate = intDate == null ? null : intDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.FIRST_DATE
     *
     * @return the value of FIS.HMFS_JM_ACT.FIRST_DATE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getFirstDate() {
        return firstDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.FIRST_DATE
     *
     * @param firstDate the value for FIS.HMFS_JM_ACT.FIRST_DATE
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setFirstDate(String firstDate) {
        this.firstDate = firstDate == null ? null : firstDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.FIRST_AMT
     *
     * @return the value of FIS.HMFS_JM_ACT.FIRST_AMT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public BigDecimal getFirstAmt() {
        return firstAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.FIRST_AMT
     *
     * @param firstAmt the value for FIS.HMFS_JM_ACT.FIRST_AMT
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setFirstAmt(BigDecimal firstAmt) {
        this.firstAmt = firstAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_ACT.ACT_STATUS
     *
     * @return the value of FIS.HMFS_JM_ACT.ACT_STATUS
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public String getActStatus() {
        return actStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_ACT.ACT_STATUS
     *
     * @param actStatus the value for FIS.HMFS_JM_ACT.ACT_STATUS
     *
     * @mbggenerated Fri Oct 17 13:00:52 CST 2014
     */
    public void setActStatus(String actStatus) {
        this.actStatus = actStatus == null ? null : actStatus.trim();
    }
}