package org.fbi.hmfsjz.repository.model;

public class HmfsJzVoucher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JZ_VOUCHER.PKID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JZ_VOUCHER.BILLNO
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JZ_VOUCHER.TXN_DATE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String txnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JZ_VOUCHER.TXN_CODE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String txnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JZ_VOUCHER.VCH_STS
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String vchSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JZ_VOUCHER.VCH_TYPE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String vchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JZ_VOUCHER.VCH_NUM
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String vchNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JZ_VOUCHER.OPER_ID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JZ_VOUCHER.ACT_TXN_SN
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String actTxnSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JZ_VOUCHER.REMARK
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JZ_VOUCHER.DEPT_ID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JZ_VOUCHER.SEND_FLAG
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String sendFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JZ_VOUCHER.TXN_TIME
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    private String txnTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JZ_VOUCHER.PKID
     *
     * @return the value of FIS.HMFS_JZ_VOUCHER.PKID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JZ_VOUCHER.PKID
     *
     * @param pkid the value for FIS.HMFS_JZ_VOUCHER.PKID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JZ_VOUCHER.BILLNO
     *
     * @return the value of FIS.HMFS_JZ_VOUCHER.BILLNO
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JZ_VOUCHER.BILLNO
     *
     * @param billno the value for FIS.HMFS_JZ_VOUCHER.BILLNO
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JZ_VOUCHER.TXN_DATE
     *
     * @return the value of FIS.HMFS_JZ_VOUCHER.TXN_DATE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getTxnDate() {
        return txnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JZ_VOUCHER.TXN_DATE
     *
     * @param txnDate the value for FIS.HMFS_JZ_VOUCHER.TXN_DATE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setTxnDate(String txnDate) {
        this.txnDate = txnDate == null ? null : txnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JZ_VOUCHER.TXN_CODE
     *
     * @return the value of FIS.HMFS_JZ_VOUCHER.TXN_CODE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getTxnCode() {
        return txnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JZ_VOUCHER.TXN_CODE
     *
     * @param txnCode the value for FIS.HMFS_JZ_VOUCHER.TXN_CODE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setTxnCode(String txnCode) {
        this.txnCode = txnCode == null ? null : txnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JZ_VOUCHER.VCH_STS
     *
     * @return the value of FIS.HMFS_JZ_VOUCHER.VCH_STS
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getVchSts() {
        return vchSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JZ_VOUCHER.VCH_STS
     *
     * @param vchSts the value for FIS.HMFS_JZ_VOUCHER.VCH_STS
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setVchSts(String vchSts) {
        this.vchSts = vchSts == null ? null : vchSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JZ_VOUCHER.VCH_TYPE
     *
     * @return the value of FIS.HMFS_JZ_VOUCHER.VCH_TYPE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getVchType() {
        return vchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JZ_VOUCHER.VCH_TYPE
     *
     * @param vchType the value for FIS.HMFS_JZ_VOUCHER.VCH_TYPE
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setVchType(String vchType) {
        this.vchType = vchType == null ? null : vchType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JZ_VOUCHER.VCH_NUM
     *
     * @return the value of FIS.HMFS_JZ_VOUCHER.VCH_NUM
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getVchNum() {
        return vchNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JZ_VOUCHER.VCH_NUM
     *
     * @param vchNum the value for FIS.HMFS_JZ_VOUCHER.VCH_NUM
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setVchNum(String vchNum) {
        this.vchNum = vchNum == null ? null : vchNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JZ_VOUCHER.OPER_ID
     *
     * @return the value of FIS.HMFS_JZ_VOUCHER.OPER_ID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JZ_VOUCHER.OPER_ID
     *
     * @param operId the value for FIS.HMFS_JZ_VOUCHER.OPER_ID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setOperId(String operId) {
        this.operId = operId == null ? null : operId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JZ_VOUCHER.ACT_TXN_SN
     *
     * @return the value of FIS.HMFS_JZ_VOUCHER.ACT_TXN_SN
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getActTxnSn() {
        return actTxnSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JZ_VOUCHER.ACT_TXN_SN
     *
     * @param actTxnSn the value for FIS.HMFS_JZ_VOUCHER.ACT_TXN_SN
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setActTxnSn(String actTxnSn) {
        this.actTxnSn = actTxnSn == null ? null : actTxnSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JZ_VOUCHER.REMARK
     *
     * @return the value of FIS.HMFS_JZ_VOUCHER.REMARK
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JZ_VOUCHER.REMARK
     *
     * @param remark the value for FIS.HMFS_JZ_VOUCHER.REMARK
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JZ_VOUCHER.DEPT_ID
     *
     * @return the value of FIS.HMFS_JZ_VOUCHER.DEPT_ID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JZ_VOUCHER.DEPT_ID
     *
     * @param deptId the value for FIS.HMFS_JZ_VOUCHER.DEPT_ID
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JZ_VOUCHER.SEND_FLAG
     *
     * @return the value of FIS.HMFS_JZ_VOUCHER.SEND_FLAG
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getSendFlag() {
        return sendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JZ_VOUCHER.SEND_FLAG
     *
     * @param sendFlag the value for FIS.HMFS_JZ_VOUCHER.SEND_FLAG
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setSendFlag(String sendFlag) {
        this.sendFlag = sendFlag == null ? null : sendFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JZ_VOUCHER.TXN_TIME
     *
     * @return the value of FIS.HMFS_JZ_VOUCHER.TXN_TIME
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getTxnTime() {
        return txnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JZ_VOUCHER.TXN_TIME
     *
     * @param txnTime the value for FIS.HMFS_JZ_VOUCHER.TXN_TIME
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setTxnTime(String txnTime) {
        this.txnTime = txnTime == null ? null : txnTime.trim();
    }
}