package org.fbi.hmfsjz.repository.model;

public class HmfsJzIrt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_IRT.PKID
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_IRT.CURCDE
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    private String curcde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_IRT.IRTCODE
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    private String irtcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_IRT.EFFDATE
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    private String effdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_IRT.IRTVALUE
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    private String irtvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_IRT.CRETLR
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    private String cretlr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_IRT.OPERDATE
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    private String operdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_IRT.RECSTS
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    private String recsts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.HMFS_JM_IRT.DAYS
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    private Short days;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_IRT.PKID
     *
     * @return the value of FIS.HMFS_JM_IRT.PKID
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_IRT.PKID
     *
     * @param pkid the value for FIS.HMFS_JM_IRT.PKID
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_IRT.CURCDE
     *
     * @return the value of FIS.HMFS_JM_IRT.CURCDE
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public String getCurcde() {
        return curcde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_IRT.CURCDE
     *
     * @param curcde the value for FIS.HMFS_JM_IRT.CURCDE
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public void setCurcde(String curcde) {
        this.curcde = curcde == null ? null : curcde.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_IRT.IRTCODE
     *
     * @return the value of FIS.HMFS_JM_IRT.IRTCODE
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public String getIrtcode() {
        return irtcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_IRT.IRTCODE
     *
     * @param irtcode the value for FIS.HMFS_JM_IRT.IRTCODE
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public void setIrtcode(String irtcode) {
        this.irtcode = irtcode == null ? null : irtcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_IRT.EFFDATE
     *
     * @return the value of FIS.HMFS_JM_IRT.EFFDATE
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public String getEffdate() {
        return effdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_IRT.EFFDATE
     *
     * @param effdate the value for FIS.HMFS_JM_IRT.EFFDATE
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public void setEffdate(String effdate) {
        this.effdate = effdate == null ? null : effdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_IRT.IRTVALUE
     *
     * @return the value of FIS.HMFS_JM_IRT.IRTVALUE
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public String getIrtvalue() {
        return irtvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_IRT.IRTVALUE
     *
     * @param irtvalue the value for FIS.HMFS_JM_IRT.IRTVALUE
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public void setIrtvalue(String irtvalue) {
        this.irtvalue = irtvalue == null ? null : irtvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_IRT.CRETLR
     *
     * @return the value of FIS.HMFS_JM_IRT.CRETLR
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public String getCretlr() {
        return cretlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_IRT.CRETLR
     *
     * @param cretlr the value for FIS.HMFS_JM_IRT.CRETLR
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public void setCretlr(String cretlr) {
        this.cretlr = cretlr == null ? null : cretlr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_IRT.OPERDATE
     *
     * @return the value of FIS.HMFS_JM_IRT.OPERDATE
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public String getOperdate() {
        return operdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_IRT.OPERDATE
     *
     * @param operdate the value for FIS.HMFS_JM_IRT.OPERDATE
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public void setOperdate(String operdate) {
        this.operdate = operdate == null ? null : operdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_IRT.RECSTS
     *
     * @return the value of FIS.HMFS_JM_IRT.RECSTS
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public String getRecsts() {
        return recsts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_IRT.RECSTS
     *
     * @param recsts the value for FIS.HMFS_JM_IRT.RECSTS
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public void setRecsts(String recsts) {
        this.recsts = recsts == null ? null : recsts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.HMFS_JM_IRT.DAYS
     *
     * @return the value of FIS.HMFS_JM_IRT.DAYS
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public Short getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.HMFS_JM_IRT.DAYS
     *
     * @param days the value for FIS.HMFS_JM_IRT.DAYS
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    public void setDays(Short days) {
        this.days = days;
    }
}