package org.fbi.hmfsjz.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class HmfsJzActDelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:19 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:19 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:19 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:19 CST 2013
     */
    public HmfsJzActDelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:19 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:19 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:19 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:19 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:19 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:19 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:19 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:19 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:19 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:19 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:19 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andHouseIdIsNull() {
            addCriterion("HOUSE_ID is null");
            return (Criteria) this;
        }

        public Criteria andHouseIdIsNotNull() {
            addCriterion("HOUSE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andHouseIdEqualTo(String value) {
            addCriterion("HOUSE_ID =", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotEqualTo(String value) {
            addCriterion("HOUSE_ID <>", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThan(String value) {
            addCriterion("HOUSE_ID >", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThanOrEqualTo(String value) {
            addCriterion("HOUSE_ID >=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThan(String value) {
            addCriterion("HOUSE_ID <", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThanOrEqualTo(String value) {
            addCriterion("HOUSE_ID <=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLike(String value) {
            addCriterion("HOUSE_ID like", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotLike(String value) {
            addCriterion("HOUSE_ID not like", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdIn(List<String> values) {
            addCriterion("HOUSE_ID in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotIn(List<String> values) {
            addCriterion("HOUSE_ID not in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdBetween(String value1, String value2) {
            addCriterion("HOUSE_ID between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotBetween(String value1, String value2) {
            addCriterion("HOUSE_ID not between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseLocationIsNull() {
            addCriterion("HOUSE_LOCATION is null");
            return (Criteria) this;
        }

        public Criteria andHouseLocationIsNotNull() {
            addCriterion("HOUSE_LOCATION is not null");
            return (Criteria) this;
        }

        public Criteria andHouseLocationEqualTo(String value) {
            addCriterion("HOUSE_LOCATION =", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationNotEqualTo(String value) {
            addCriterion("HOUSE_LOCATION <>", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationGreaterThan(String value) {
            addCriterion("HOUSE_LOCATION >", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationGreaterThanOrEqualTo(String value) {
            addCriterion("HOUSE_LOCATION >=", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationLessThan(String value) {
            addCriterion("HOUSE_LOCATION <", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationLessThanOrEqualTo(String value) {
            addCriterion("HOUSE_LOCATION <=", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationLike(String value) {
            addCriterion("HOUSE_LOCATION like", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationNotLike(String value) {
            addCriterion("HOUSE_LOCATION not like", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationIn(List<String> values) {
            addCriterion("HOUSE_LOCATION in", values, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationNotIn(List<String> values) {
            addCriterion("HOUSE_LOCATION not in", values, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationBetween(String value1, String value2) {
            addCriterion("HOUSE_LOCATION between", value1, value2, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationNotBetween(String value1, String value2) {
            addCriterion("HOUSE_LOCATION not between", value1, value2, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseAreaIsNull() {
            addCriterion("HOUSE_AREA is null");
            return (Criteria) this;
        }

        public Criteria andHouseAreaIsNotNull() {
            addCriterion("HOUSE_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andHouseAreaEqualTo(String value) {
            addCriterion("HOUSE_AREA =", value, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaNotEqualTo(String value) {
            addCriterion("HOUSE_AREA <>", value, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaGreaterThan(String value) {
            addCriterion("HOUSE_AREA >", value, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaGreaterThanOrEqualTo(String value) {
            addCriterion("HOUSE_AREA >=", value, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaLessThan(String value) {
            addCriterion("HOUSE_AREA <", value, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaLessThanOrEqualTo(String value) {
            addCriterion("HOUSE_AREA <=", value, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaLike(String value) {
            addCriterion("HOUSE_AREA like", value, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaNotLike(String value) {
            addCriterion("HOUSE_AREA not like", value, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaIn(List<String> values) {
            addCriterion("HOUSE_AREA in", values, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaNotIn(List<String> values) {
            addCriterion("HOUSE_AREA not in", values, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaBetween(String value1, String value2) {
            addCriterion("HOUSE_AREA between", value1, value2, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaNotBetween(String value1, String value2) {
            addCriterion("HOUSE_AREA not between", value1, value2, "houseArea");
            return (Criteria) this;
        }

        public Criteria andStandardIsNull() {
            addCriterion("STANDARD is null");
            return (Criteria) this;
        }

        public Criteria andStandardIsNotNull() {
            addCriterion("STANDARD is not null");
            return (Criteria) this;
        }

        public Criteria andStandardEqualTo(String value) {
            addCriterion("STANDARD =", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardNotEqualTo(String value) {
            addCriterion("STANDARD <>", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardGreaterThan(String value) {
            addCriterion("STANDARD >", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardGreaterThanOrEqualTo(String value) {
            addCriterion("STANDARD >=", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardLessThan(String value) {
            addCriterion("STANDARD <", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardLessThanOrEqualTo(String value) {
            addCriterion("STANDARD <=", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardLike(String value) {
            addCriterion("STANDARD like", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardNotLike(String value) {
            addCriterion("STANDARD not like", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardIn(List<String> values) {
            addCriterion("STANDARD in", values, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardNotIn(List<String> values) {
            addCriterion("STANDARD not in", values, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardBetween(String value1, String value2) {
            addCriterion("STANDARD between", value1, value2, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardNotBetween(String value1, String value2) {
            addCriterion("STANDARD not between", value1, value2, "standard");
            return (Criteria) this;
        }

        public Criteria andBalAmtIsNull() {
            addCriterion("BAL_AMT is null");
            return (Criteria) this;
        }

        public Criteria andBalAmtIsNotNull() {
            addCriterion("BAL_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andBalAmtEqualTo(BigDecimal value) {
            addCriterion("BAL_AMT =", value, "balAmt");
            return (Criteria) this;
        }

        public Criteria andBalAmtNotEqualTo(BigDecimal value) {
            addCriterion("BAL_AMT <>", value, "balAmt");
            return (Criteria) this;
        }

        public Criteria andBalAmtGreaterThan(BigDecimal value) {
            addCriterion("BAL_AMT >", value, "balAmt");
            return (Criteria) this;
        }

        public Criteria andBalAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BAL_AMT >=", value, "balAmt");
            return (Criteria) this;
        }

        public Criteria andBalAmtLessThan(BigDecimal value) {
            addCriterion("BAL_AMT <", value, "balAmt");
            return (Criteria) this;
        }

        public Criteria andBalAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BAL_AMT <=", value, "balAmt");
            return (Criteria) this;
        }

        public Criteria andBalAmtIn(List<BigDecimal> values) {
            addCriterion("BAL_AMT in", values, "balAmt");
            return (Criteria) this;
        }

        public Criteria andBalAmtNotIn(List<BigDecimal> values) {
            addCriterion("BAL_AMT not in", values, "balAmt");
            return (Criteria) this;
        }

        public Criteria andBalAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BAL_AMT between", value1, value2, "balAmt");
            return (Criteria) this;
        }

        public Criteria andBalAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BAL_AMT not between", value1, value2, "balAmt");
            return (Criteria) this;
        }

        public Criteria andAreaAccountIsNull() {
            addCriterion("AREA_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andAreaAccountIsNotNull() {
            addCriterion("AREA_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andAreaAccountEqualTo(String value) {
            addCriterion("AREA_ACCOUNT =", value, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountNotEqualTo(String value) {
            addCriterion("AREA_ACCOUNT <>", value, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountGreaterThan(String value) {
            addCriterion("AREA_ACCOUNT >", value, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountGreaterThanOrEqualTo(String value) {
            addCriterion("AREA_ACCOUNT >=", value, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountLessThan(String value) {
            addCriterion("AREA_ACCOUNT <", value, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountLessThanOrEqualTo(String value) {
            addCriterion("AREA_ACCOUNT <=", value, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountLike(String value) {
            addCriterion("AREA_ACCOUNT like", value, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountNotLike(String value) {
            addCriterion("AREA_ACCOUNT not like", value, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountIn(List<String> values) {
            addCriterion("AREA_ACCOUNT in", values, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountNotIn(List<String> values) {
            addCriterion("AREA_ACCOUNT not in", values, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountBetween(String value1, String value2) {
            addCriterion("AREA_ACCOUNT between", value1, value2, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountNotBetween(String value1, String value2) {
            addCriterion("AREA_ACCOUNT not between", value1, value2, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountIsNull() {
            addCriterion("HOUSE_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andHouseAccountIsNotNull() {
            addCriterion("HOUSE_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andHouseAccountEqualTo(String value) {
            addCriterion("HOUSE_ACCOUNT =", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountNotEqualTo(String value) {
            addCriterion("HOUSE_ACCOUNT <>", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountGreaterThan(String value) {
            addCriterion("HOUSE_ACCOUNT >", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountGreaterThanOrEqualTo(String value) {
            addCriterion("HOUSE_ACCOUNT >=", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountLessThan(String value) {
            addCriterion("HOUSE_ACCOUNT <", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountLessThanOrEqualTo(String value) {
            addCriterion("HOUSE_ACCOUNT <=", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountLike(String value) {
            addCriterion("HOUSE_ACCOUNT like", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountNotLike(String value) {
            addCriterion("HOUSE_ACCOUNT not like", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountIn(List<String> values) {
            addCriterion("HOUSE_ACCOUNT in", values, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountNotIn(List<String> values) {
            addCriterion("HOUSE_ACCOUNT not in", values, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountBetween(String value1, String value2) {
            addCriterion("HOUSE_ACCOUNT between", value1, value2, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountNotBetween(String value1, String value2) {
            addCriterion("HOUSE_ACCOUNT not between", value1, value2, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNull() {
            addCriterion("CARD_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNotNull() {
            addCriterion("CARD_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCardTypeEqualTo(String value) {
            addCriterion("CARD_TYPE =", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotEqualTo(String value) {
            addCriterion("CARD_TYPE <>", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThan(String value) {
            addCriterion("CARD_TYPE >", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_TYPE >=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThan(String value) {
            addCriterion("CARD_TYPE <", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThanOrEqualTo(String value) {
            addCriterion("CARD_TYPE <=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLike(String value) {
            addCriterion("CARD_TYPE like", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotLike(String value) {
            addCriterion("CARD_TYPE not like", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeIn(List<String> values) {
            addCriterion("CARD_TYPE in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotIn(List<String> values) {
            addCriterion("CARD_TYPE not in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeBetween(String value1, String value2) {
            addCriterion("CARD_TYPE between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotBetween(String value1, String value2) {
            addCriterion("CARD_TYPE not between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNull() {
            addCriterion("CARD_NO is null");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNotNull() {
            addCriterion("CARD_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoEqualTo(String value) {
            addCriterion("CARD_NO =", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotEqualTo(String value) {
            addCriterion("CARD_NO <>", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThan(String value) {
            addCriterion("CARD_NO >", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_NO >=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThan(String value) {
            addCriterion("CARD_NO <", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThanOrEqualTo(String value) {
            addCriterion("CARD_NO <=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLike(String value) {
            addCriterion("CARD_NO like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotLike(String value) {
            addCriterion("CARD_NO not like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoIn(List<String> values) {
            addCriterion("CARD_NO in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotIn(List<String> values) {
            addCriterion("CARD_NO not in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoBetween(String value1, String value2) {
            addCriterion("CARD_NO between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotBetween(String value1, String value2) {
            addCriterion("CARD_NO not between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNull() {
            addCriterion("OWNER is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNotNull() {
            addCriterion("OWNER is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(String value) {
            addCriterion("OWNER =", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotEqualTo(String value) {
            addCriterion("OWNER <>", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThan(String value) {
            addCriterion("OWNER >", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("OWNER >=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThan(String value) {
            addCriterion("OWNER <", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThanOrEqualTo(String value) {
            addCriterion("OWNER <=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLike(String value) {
            addCriterion("OWNER like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotLike(String value) {
            addCriterion("OWNER not like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerIn(List<String> values) {
            addCriterion("OWNER in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotIn(List<String> values) {
            addCriterion("OWNER not in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerBetween(String value1, String value2) {
            addCriterion("OWNER between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotBetween(String value1, String value2) {
            addCriterion("OWNER not between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("TEL is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("TEL is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("TEL =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("TEL <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("TEL >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("TEL >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("TEL <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("TEL <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("TEL like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("TEL not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("TEL in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("TEL not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("TEL between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("TEL not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andReserveIsNull() {
            addCriterion("RESERVE is null");
            return (Criteria) this;
        }

        public Criteria andReserveIsNotNull() {
            addCriterion("RESERVE is not null");
            return (Criteria) this;
        }

        public Criteria andReserveEqualTo(String value) {
            addCriterion("RESERVE =", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveNotEqualTo(String value) {
            addCriterion("RESERVE <>", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveGreaterThan(String value) {
            addCriterion("RESERVE >", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveGreaterThanOrEqualTo(String value) {
            addCriterion("RESERVE >=", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveLessThan(String value) {
            addCriterion("RESERVE <", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveLessThanOrEqualTo(String value) {
            addCriterion("RESERVE <=", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveLike(String value) {
            addCriterion("RESERVE like", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveNotLike(String value) {
            addCriterion("RESERVE not like", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveIn(List<String> values) {
            addCriterion("RESERVE in", values, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveNotIn(List<String> values) {
            addCriterion("RESERVE not in", values, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveBetween(String value1, String value2) {
            addCriterion("RESERVE between", value1, value2, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveNotBetween(String value1, String value2) {
            addCriterion("RESERVE not between", value1, value2, "reserve");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNull() {
            addCriterion("OPER_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNotNull() {
            addCriterion("OPER_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOperDateEqualTo(String value) {
            addCriterion("OPER_DATE =", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotEqualTo(String value) {
            addCriterion("OPER_DATE <>", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThan(String value) {
            addCriterion("OPER_DATE >", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_DATE >=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThan(String value) {
            addCriterion("OPER_DATE <", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThanOrEqualTo(String value) {
            addCriterion("OPER_DATE <=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLike(String value) {
            addCriterion("OPER_DATE like", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotLike(String value) {
            addCriterion("OPER_DATE not like", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateIn(List<String> values) {
            addCriterion("OPER_DATE in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotIn(List<String> values) {
            addCriterion("OPER_DATE not in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateBetween(String value1, String value2) {
            addCriterion("OPER_DATE between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotBetween(String value1, String value2) {
            addCriterion("OPER_DATE not between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperTimeIsNull() {
            addCriterion("OPER_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOperTimeIsNotNull() {
            addCriterion("OPER_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOperTimeEqualTo(String value) {
            addCriterion("OPER_TIME =", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotEqualTo(String value) {
            addCriterion("OPER_TIME <>", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeGreaterThan(String value) {
            addCriterion("OPER_TIME >", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_TIME >=", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLessThan(String value) {
            addCriterion("OPER_TIME <", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLessThanOrEqualTo(String value) {
            addCriterion("OPER_TIME <=", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLike(String value) {
            addCriterion("OPER_TIME like", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotLike(String value) {
            addCriterion("OPER_TIME not like", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeIn(List<String> values) {
            addCriterion("OPER_TIME in", values, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotIn(List<String> values) {
            addCriterion("OPER_TIME not in", values, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeBetween(String value1, String value2) {
            addCriterion("OPER_TIME between", value1, value2, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotBetween(String value1, String value2) {
            addCriterion("OPER_TIME not between", value1, value2, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNull() {
            addCriterion("OPER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNotNull() {
            addCriterion("OPER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOperIdEqualTo(String value) {
            addCriterion("OPER_ID =", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotEqualTo(String value) {
            addCriterion("OPER_ID <>", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThan(String value) {
            addCriterion("OPER_ID >", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_ID >=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThan(String value) {
            addCriterion("OPER_ID <", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThanOrEqualTo(String value) {
            addCriterion("OPER_ID <=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLike(String value) {
            addCriterion("OPER_ID like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotLike(String value) {
            addCriterion("OPER_ID not like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdIn(List<String> values) {
            addCriterion("OPER_ID in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotIn(List<String> values) {
            addCriterion("OPER_ID not in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdBetween(String value1, String value2) {
            addCriterion("OPER_ID between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotBetween(String value1, String value2) {
            addCriterion("OPER_ID not between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andIntAmtIsNull() {
            addCriterion("INT_AMT is null");
            return (Criteria) this;
        }

        public Criteria andIntAmtIsNotNull() {
            addCriterion("INT_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andIntAmtEqualTo(BigDecimal value) {
            addCriterion("INT_AMT =", value, "intAmt");
            return (Criteria) this;
        }

        public Criteria andIntAmtNotEqualTo(BigDecimal value) {
            addCriterion("INT_AMT <>", value, "intAmt");
            return (Criteria) this;
        }

        public Criteria andIntAmtGreaterThan(BigDecimal value) {
            addCriterion("INT_AMT >", value, "intAmt");
            return (Criteria) this;
        }

        public Criteria andIntAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INT_AMT >=", value, "intAmt");
            return (Criteria) this;
        }

        public Criteria andIntAmtLessThan(BigDecimal value) {
            addCriterion("INT_AMT <", value, "intAmt");
            return (Criteria) this;
        }

        public Criteria andIntAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INT_AMT <=", value, "intAmt");
            return (Criteria) this;
        }

        public Criteria andIntAmtIn(List<BigDecimal> values) {
            addCriterion("INT_AMT in", values, "intAmt");
            return (Criteria) this;
        }

        public Criteria andIntAmtNotIn(List<BigDecimal> values) {
            addCriterion("INT_AMT not in", values, "intAmt");
            return (Criteria) this;
        }

        public Criteria andIntAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INT_AMT between", value1, value2, "intAmt");
            return (Criteria) this;
        }

        public Criteria andIntAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INT_AMT not between", value1, value2, "intAmt");
            return (Criteria) this;
        }

        public Criteria andMngAmtIsNull() {
            addCriterion("MNG_AMT is null");
            return (Criteria) this;
        }

        public Criteria andMngAmtIsNotNull() {
            addCriterion("MNG_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andMngAmtEqualTo(BigDecimal value) {
            addCriterion("MNG_AMT =", value, "mngAmt");
            return (Criteria) this;
        }

        public Criteria andMngAmtNotEqualTo(BigDecimal value) {
            addCriterion("MNG_AMT <>", value, "mngAmt");
            return (Criteria) this;
        }

        public Criteria andMngAmtGreaterThan(BigDecimal value) {
            addCriterion("MNG_AMT >", value, "mngAmt");
            return (Criteria) this;
        }

        public Criteria andMngAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MNG_AMT >=", value, "mngAmt");
            return (Criteria) this;
        }

        public Criteria andMngAmtLessThan(BigDecimal value) {
            addCriterion("MNG_AMT <", value, "mngAmt");
            return (Criteria) this;
        }

        public Criteria andMngAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MNG_AMT <=", value, "mngAmt");
            return (Criteria) this;
        }

        public Criteria andMngAmtIn(List<BigDecimal> values) {
            addCriterion("MNG_AMT in", values, "mngAmt");
            return (Criteria) this;
        }

        public Criteria andMngAmtNotIn(List<BigDecimal> values) {
            addCriterion("MNG_AMT not in", values, "mngAmt");
            return (Criteria) this;
        }

        public Criteria andMngAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MNG_AMT between", value1, value2, "mngAmt");
            return (Criteria) this;
        }

        public Criteria andMngAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MNG_AMT not between", value1, value2, "mngAmt");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("DEPT_ID is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("DEPT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(String value) {
            addCriterion("DEPT_ID =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(String value) {
            addCriterion("DEPT_ID <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(String value) {
            addCriterion("DEPT_ID >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT_ID >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(String value) {
            addCriterion("DEPT_ID <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(String value) {
            addCriterion("DEPT_ID <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLike(String value) {
            addCriterion("DEPT_ID like", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotLike(String value) {
            addCriterion("DEPT_ID not like", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<String> values) {
            addCriterion("DEPT_ID in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<String> values) {
            addCriterion("DEPT_ID not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(String value1, String value2) {
            addCriterion("DEPT_ID between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(String value1, String value2) {
            addCriterion("DEPT_ID not between", value1, value2, "deptId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 19 16:19:19 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:19 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}