package org.fbi.hmfsjz.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class HmfsJzRefundExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public HmfsJzRefundExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andBillnoIsNull() {
            addCriterion("BILLNO is null");
            return (Criteria) this;
        }

        public Criteria andBillnoIsNotNull() {
            addCriterion("BILLNO is not null");
            return (Criteria) this;
        }

        public Criteria andBillnoEqualTo(String value) {
            addCriterion("BILLNO =", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoNotEqualTo(String value) {
            addCriterion("BILLNO <>", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoGreaterThan(String value) {
            addCriterion("BILLNO >", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoGreaterThanOrEqualTo(String value) {
            addCriterion("BILLNO >=", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoLessThan(String value) {
            addCriterion("BILLNO <", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoLessThanOrEqualTo(String value) {
            addCriterion("BILLNO <=", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoLike(String value) {
            addCriterion("BILLNO like", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoNotLike(String value) {
            addCriterion("BILLNO not like", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoIn(List<String> values) {
            addCriterion("BILLNO in", values, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoNotIn(List<String> values) {
            addCriterion("BILLNO not in", values, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoBetween(String value1, String value2) {
            addCriterion("BILLNO between", value1, value2, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoNotBetween(String value1, String value2) {
            addCriterion("BILLNO not between", value1, value2, "billno");
            return (Criteria) this;
        }

        public Criteria andBillStsCodeIsNull() {
            addCriterion("BILL_STS_CODE is null");
            return (Criteria) this;
        }

        public Criteria andBillStsCodeIsNotNull() {
            addCriterion("BILL_STS_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andBillStsCodeEqualTo(String value) {
            addCriterion("BILL_STS_CODE =", value, "billStsCode");
            return (Criteria) this;
        }

        public Criteria andBillStsCodeNotEqualTo(String value) {
            addCriterion("BILL_STS_CODE <>", value, "billStsCode");
            return (Criteria) this;
        }

        public Criteria andBillStsCodeGreaterThan(String value) {
            addCriterion("BILL_STS_CODE >", value, "billStsCode");
            return (Criteria) this;
        }

        public Criteria andBillStsCodeGreaterThanOrEqualTo(String value) {
            addCriterion("BILL_STS_CODE >=", value, "billStsCode");
            return (Criteria) this;
        }

        public Criteria andBillStsCodeLessThan(String value) {
            addCriterion("BILL_STS_CODE <", value, "billStsCode");
            return (Criteria) this;
        }

        public Criteria andBillStsCodeLessThanOrEqualTo(String value) {
            addCriterion("BILL_STS_CODE <=", value, "billStsCode");
            return (Criteria) this;
        }

        public Criteria andBillStsCodeLike(String value) {
            addCriterion("BILL_STS_CODE like", value, "billStsCode");
            return (Criteria) this;
        }

        public Criteria andBillStsCodeNotLike(String value) {
            addCriterion("BILL_STS_CODE not like", value, "billStsCode");
            return (Criteria) this;
        }

        public Criteria andBillStsCodeIn(List<String> values) {
            addCriterion("BILL_STS_CODE in", values, "billStsCode");
            return (Criteria) this;
        }

        public Criteria andBillStsCodeNotIn(List<String> values) {
            addCriterion("BILL_STS_CODE not in", values, "billStsCode");
            return (Criteria) this;
        }

        public Criteria andBillStsCodeBetween(String value1, String value2) {
            addCriterion("BILL_STS_CODE between", value1, value2, "billStsCode");
            return (Criteria) this;
        }

        public Criteria andBillStsCodeNotBetween(String value1, String value2) {
            addCriterion("BILL_STS_CODE not between", value1, value2, "billStsCode");
            return (Criteria) this;
        }

        public Criteria andBillStsTitleIsNull() {
            addCriterion("BILL_STS_TITLE is null");
            return (Criteria) this;
        }

        public Criteria andBillStsTitleIsNotNull() {
            addCriterion("BILL_STS_TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andBillStsTitleEqualTo(String value) {
            addCriterion("BILL_STS_TITLE =", value, "billStsTitle");
            return (Criteria) this;
        }

        public Criteria andBillStsTitleNotEqualTo(String value) {
            addCriterion("BILL_STS_TITLE <>", value, "billStsTitle");
            return (Criteria) this;
        }

        public Criteria andBillStsTitleGreaterThan(String value) {
            addCriterion("BILL_STS_TITLE >", value, "billStsTitle");
            return (Criteria) this;
        }

        public Criteria andBillStsTitleGreaterThanOrEqualTo(String value) {
            addCriterion("BILL_STS_TITLE >=", value, "billStsTitle");
            return (Criteria) this;
        }

        public Criteria andBillStsTitleLessThan(String value) {
            addCriterion("BILL_STS_TITLE <", value, "billStsTitle");
            return (Criteria) this;
        }

        public Criteria andBillStsTitleLessThanOrEqualTo(String value) {
            addCriterion("BILL_STS_TITLE <=", value, "billStsTitle");
            return (Criteria) this;
        }

        public Criteria andBillStsTitleLike(String value) {
            addCriterion("BILL_STS_TITLE like", value, "billStsTitle");
            return (Criteria) this;
        }

        public Criteria andBillStsTitleNotLike(String value) {
            addCriterion("BILL_STS_TITLE not like", value, "billStsTitle");
            return (Criteria) this;
        }

        public Criteria andBillStsTitleIn(List<String> values) {
            addCriterion("BILL_STS_TITLE in", values, "billStsTitle");
            return (Criteria) this;
        }

        public Criteria andBillStsTitleNotIn(List<String> values) {
            addCriterion("BILL_STS_TITLE not in", values, "billStsTitle");
            return (Criteria) this;
        }

        public Criteria andBillStsTitleBetween(String value1, String value2) {
            addCriterion("BILL_STS_TITLE between", value1, value2, "billStsTitle");
            return (Criteria) this;
        }

        public Criteria andBillStsTitleNotBetween(String value1, String value2) {
            addCriterion("BILL_STS_TITLE not between", value1, value2, "billStsTitle");
            return (Criteria) this;
        }

        public Criteria andHouseIdIsNull() {
            addCriterion("HOUSE_ID is null");
            return (Criteria) this;
        }

        public Criteria andHouseIdIsNotNull() {
            addCriterion("HOUSE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andHouseIdEqualTo(String value) {
            addCriterion("HOUSE_ID =", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotEqualTo(String value) {
            addCriterion("HOUSE_ID <>", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThan(String value) {
            addCriterion("HOUSE_ID >", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThanOrEqualTo(String value) {
            addCriterion("HOUSE_ID >=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThan(String value) {
            addCriterion("HOUSE_ID <", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThanOrEqualTo(String value) {
            addCriterion("HOUSE_ID <=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLike(String value) {
            addCriterion("HOUSE_ID like", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotLike(String value) {
            addCriterion("HOUSE_ID not like", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdIn(List<String> values) {
            addCriterion("HOUSE_ID in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotIn(List<String> values) {
            addCriterion("HOUSE_ID not in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdBetween(String value1, String value2) {
            addCriterion("HOUSE_ID between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotBetween(String value1, String value2) {
            addCriterion("HOUSE_ID not between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseLocationIsNull() {
            addCriterion("HOUSE_LOCATION is null");
            return (Criteria) this;
        }

        public Criteria andHouseLocationIsNotNull() {
            addCriterion("HOUSE_LOCATION is not null");
            return (Criteria) this;
        }

        public Criteria andHouseLocationEqualTo(String value) {
            addCriterion("HOUSE_LOCATION =", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationNotEqualTo(String value) {
            addCriterion("HOUSE_LOCATION <>", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationGreaterThan(String value) {
            addCriterion("HOUSE_LOCATION >", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationGreaterThanOrEqualTo(String value) {
            addCriterion("HOUSE_LOCATION >=", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationLessThan(String value) {
            addCriterion("HOUSE_LOCATION <", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationLessThanOrEqualTo(String value) {
            addCriterion("HOUSE_LOCATION <=", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationLike(String value) {
            addCriterion("HOUSE_LOCATION like", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationNotLike(String value) {
            addCriterion("HOUSE_LOCATION not like", value, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationIn(List<String> values) {
            addCriterion("HOUSE_LOCATION in", values, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationNotIn(List<String> values) {
            addCriterion("HOUSE_LOCATION not in", values, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationBetween(String value1, String value2) {
            addCriterion("HOUSE_LOCATION between", value1, value2, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseLocationNotBetween(String value1, String value2) {
            addCriterion("HOUSE_LOCATION not between", value1, value2, "houseLocation");
            return (Criteria) this;
        }

        public Criteria andHouseAreaIsNull() {
            addCriterion("HOUSE_AREA is null");
            return (Criteria) this;
        }

        public Criteria andHouseAreaIsNotNull() {
            addCriterion("HOUSE_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andHouseAreaEqualTo(String value) {
            addCriterion("HOUSE_AREA =", value, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaNotEqualTo(String value) {
            addCriterion("HOUSE_AREA <>", value, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaGreaterThan(String value) {
            addCriterion("HOUSE_AREA >", value, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaGreaterThanOrEqualTo(String value) {
            addCriterion("HOUSE_AREA >=", value, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaLessThan(String value) {
            addCriterion("HOUSE_AREA <", value, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaLessThanOrEqualTo(String value) {
            addCriterion("HOUSE_AREA <=", value, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaLike(String value) {
            addCriterion("HOUSE_AREA like", value, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaNotLike(String value) {
            addCriterion("HOUSE_AREA not like", value, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaIn(List<String> values) {
            addCriterion("HOUSE_AREA in", values, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaNotIn(List<String> values) {
            addCriterion("HOUSE_AREA not in", values, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaBetween(String value1, String value2) {
            addCriterion("HOUSE_AREA between", value1, value2, "houseArea");
            return (Criteria) this;
        }

        public Criteria andHouseAreaNotBetween(String value1, String value2) {
            addCriterion("HOUSE_AREA not between", value1, value2, "houseArea");
            return (Criteria) this;
        }

        public Criteria andStandardIsNull() {
            addCriterion("STANDARD is null");
            return (Criteria) this;
        }

        public Criteria andStandardIsNotNull() {
            addCriterion("STANDARD is not null");
            return (Criteria) this;
        }

        public Criteria andStandardEqualTo(String value) {
            addCriterion("STANDARD =", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardNotEqualTo(String value) {
            addCriterion("STANDARD <>", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardGreaterThan(String value) {
            addCriterion("STANDARD >", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardGreaterThanOrEqualTo(String value) {
            addCriterion("STANDARD >=", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardLessThan(String value) {
            addCriterion("STANDARD <", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardLessThanOrEqualTo(String value) {
            addCriterion("STANDARD <=", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardLike(String value) {
            addCriterion("STANDARD like", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardNotLike(String value) {
            addCriterion("STANDARD not like", value, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardIn(List<String> values) {
            addCriterion("STANDARD in", values, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardNotIn(List<String> values) {
            addCriterion("STANDARD not in", values, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardBetween(String value1, String value2) {
            addCriterion("STANDARD between", value1, value2, "standard");
            return (Criteria) this;
        }

        public Criteria andStandardNotBetween(String value1, String value2) {
            addCriterion("STANDARD not between", value1, value2, "standard");
            return (Criteria) this;
        }

        public Criteria andTxnAmtIsNull() {
            addCriterion("TXN_AMT is null");
            return (Criteria) this;
        }

        public Criteria andTxnAmtIsNotNull() {
            addCriterion("TXN_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andTxnAmtEqualTo(BigDecimal value) {
            addCriterion("TXN_AMT =", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtNotEqualTo(BigDecimal value) {
            addCriterion("TXN_AMT <>", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtGreaterThan(BigDecimal value) {
            addCriterion("TXN_AMT >", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TXN_AMT >=", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtLessThan(BigDecimal value) {
            addCriterion("TXN_AMT <", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TXN_AMT <=", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtIn(List<BigDecimal> values) {
            addCriterion("TXN_AMT in", values, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtNotIn(List<BigDecimal> values) {
            addCriterion("TXN_AMT not in", values, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TXN_AMT between", value1, value2, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TXN_AMT not between", value1, value2, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andPayBankIsNull() {
            addCriterion("PAY_BANK is null");
            return (Criteria) this;
        }

        public Criteria andPayBankIsNotNull() {
            addCriterion("PAY_BANK is not null");
            return (Criteria) this;
        }

        public Criteria andPayBankEqualTo(String value) {
            addCriterion("PAY_BANK =", value, "payBank");
            return (Criteria) this;
        }

        public Criteria andPayBankNotEqualTo(String value) {
            addCriterion("PAY_BANK <>", value, "payBank");
            return (Criteria) this;
        }

        public Criteria andPayBankGreaterThan(String value) {
            addCriterion("PAY_BANK >", value, "payBank");
            return (Criteria) this;
        }

        public Criteria andPayBankGreaterThanOrEqualTo(String value) {
            addCriterion("PAY_BANK >=", value, "payBank");
            return (Criteria) this;
        }

        public Criteria andPayBankLessThan(String value) {
            addCriterion("PAY_BANK <", value, "payBank");
            return (Criteria) this;
        }

        public Criteria andPayBankLessThanOrEqualTo(String value) {
            addCriterion("PAY_BANK <=", value, "payBank");
            return (Criteria) this;
        }

        public Criteria andPayBankLike(String value) {
            addCriterion("PAY_BANK like", value, "payBank");
            return (Criteria) this;
        }

        public Criteria andPayBankNotLike(String value) {
            addCriterion("PAY_BANK not like", value, "payBank");
            return (Criteria) this;
        }

        public Criteria andPayBankIn(List<String> values) {
            addCriterion("PAY_BANK in", values, "payBank");
            return (Criteria) this;
        }

        public Criteria andPayBankNotIn(List<String> values) {
            addCriterion("PAY_BANK not in", values, "payBank");
            return (Criteria) this;
        }

        public Criteria andPayBankBetween(String value1, String value2) {
            addCriterion("PAY_BANK between", value1, value2, "payBank");
            return (Criteria) this;
        }

        public Criteria andPayBankNotBetween(String value1, String value2) {
            addCriterion("PAY_BANK not between", value1, value2, "payBank");
            return (Criteria) this;
        }

        public Criteria andAreaAccountIsNull() {
            addCriterion("AREA_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andAreaAccountIsNotNull() {
            addCriterion("AREA_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andAreaAccountEqualTo(String value) {
            addCriterion("AREA_ACCOUNT =", value, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountNotEqualTo(String value) {
            addCriterion("AREA_ACCOUNT <>", value, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountGreaterThan(String value) {
            addCriterion("AREA_ACCOUNT >", value, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountGreaterThanOrEqualTo(String value) {
            addCriterion("AREA_ACCOUNT >=", value, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountLessThan(String value) {
            addCriterion("AREA_ACCOUNT <", value, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountLessThanOrEqualTo(String value) {
            addCriterion("AREA_ACCOUNT <=", value, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountLike(String value) {
            addCriterion("AREA_ACCOUNT like", value, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountNotLike(String value) {
            addCriterion("AREA_ACCOUNT not like", value, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountIn(List<String> values) {
            addCriterion("AREA_ACCOUNT in", values, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountNotIn(List<String> values) {
            addCriterion("AREA_ACCOUNT not in", values, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountBetween(String value1, String value2) {
            addCriterion("AREA_ACCOUNT between", value1, value2, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andAreaAccountNotBetween(String value1, String value2) {
            addCriterion("AREA_ACCOUNT not between", value1, value2, "areaAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountIsNull() {
            addCriterion("HOUSE_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andHouseAccountIsNotNull() {
            addCriterion("HOUSE_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andHouseAccountEqualTo(String value) {
            addCriterion("HOUSE_ACCOUNT =", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountNotEqualTo(String value) {
            addCriterion("HOUSE_ACCOUNT <>", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountGreaterThan(String value) {
            addCriterion("HOUSE_ACCOUNT >", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountGreaterThanOrEqualTo(String value) {
            addCriterion("HOUSE_ACCOUNT >=", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountLessThan(String value) {
            addCriterion("HOUSE_ACCOUNT <", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountLessThanOrEqualTo(String value) {
            addCriterion("HOUSE_ACCOUNT <=", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountLike(String value) {
            addCriterion("HOUSE_ACCOUNT like", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountNotLike(String value) {
            addCriterion("HOUSE_ACCOUNT not like", value, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountIn(List<String> values) {
            addCriterion("HOUSE_ACCOUNT in", values, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountNotIn(List<String> values) {
            addCriterion("HOUSE_ACCOUNT not in", values, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountBetween(String value1, String value2) {
            addCriterion("HOUSE_ACCOUNT between", value1, value2, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andHouseAccountNotBetween(String value1, String value2) {
            addCriterion("HOUSE_ACCOUNT not between", value1, value2, "houseAccount");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNull() {
            addCriterion("CARD_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCardTypeIsNotNull() {
            addCriterion("CARD_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCardTypeEqualTo(String value) {
            addCriterion("CARD_TYPE =", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotEqualTo(String value) {
            addCriterion("CARD_TYPE <>", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThan(String value) {
            addCriterion("CARD_TYPE >", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_TYPE >=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThan(String value) {
            addCriterion("CARD_TYPE <", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLessThanOrEqualTo(String value) {
            addCriterion("CARD_TYPE <=", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeLike(String value) {
            addCriterion("CARD_TYPE like", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotLike(String value) {
            addCriterion("CARD_TYPE not like", value, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeIn(List<String> values) {
            addCriterion("CARD_TYPE in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotIn(List<String> values) {
            addCriterion("CARD_TYPE not in", values, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeBetween(String value1, String value2) {
            addCriterion("CARD_TYPE between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardTypeNotBetween(String value1, String value2) {
            addCriterion("CARD_TYPE not between", value1, value2, "cardType");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNull() {
            addCriterion("CARD_NO is null");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNotNull() {
            addCriterion("CARD_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoEqualTo(String value) {
            addCriterion("CARD_NO =", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotEqualTo(String value) {
            addCriterion("CARD_NO <>", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThan(String value) {
            addCriterion("CARD_NO >", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_NO >=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThan(String value) {
            addCriterion("CARD_NO <", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThanOrEqualTo(String value) {
            addCriterion("CARD_NO <=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLike(String value) {
            addCriterion("CARD_NO like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotLike(String value) {
            addCriterion("CARD_NO not like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoIn(List<String> values) {
            addCriterion("CARD_NO in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotIn(List<String> values) {
            addCriterion("CARD_NO not in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoBetween(String value1, String value2) {
            addCriterion("CARD_NO between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotBetween(String value1, String value2) {
            addCriterion("CARD_NO not between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNull() {
            addCriterion("OWNER is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIsNotNull() {
            addCriterion("OWNER is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerEqualTo(String value) {
            addCriterion("OWNER =", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotEqualTo(String value) {
            addCriterion("OWNER <>", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThan(String value) {
            addCriterion("OWNER >", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("OWNER >=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThan(String value) {
            addCriterion("OWNER <", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLessThanOrEqualTo(String value) {
            addCriterion("OWNER <=", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerLike(String value) {
            addCriterion("OWNER like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotLike(String value) {
            addCriterion("OWNER not like", value, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerIn(List<String> values) {
            addCriterion("OWNER in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotIn(List<String> values) {
            addCriterion("OWNER not in", values, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerBetween(String value1, String value2) {
            addCriterion("OWNER between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andOwnerNotBetween(String value1, String value2) {
            addCriterion("OWNER not between", value1, value2, "owner");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("TEL is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("TEL is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("TEL =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("TEL <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("TEL >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("TEL >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("TEL <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("TEL <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("TEL like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("TEL not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("TEL in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("TEL not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("TEL between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("TEL not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andReserveIsNull() {
            addCriterion("RESERVE is null");
            return (Criteria) this;
        }

        public Criteria andReserveIsNotNull() {
            addCriterion("RESERVE is not null");
            return (Criteria) this;
        }

        public Criteria andReserveEqualTo(String value) {
            addCriterion("RESERVE =", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveNotEqualTo(String value) {
            addCriterion("RESERVE <>", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveGreaterThan(String value) {
            addCriterion("RESERVE >", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveGreaterThanOrEqualTo(String value) {
            addCriterion("RESERVE >=", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveLessThan(String value) {
            addCriterion("RESERVE <", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveLessThanOrEqualTo(String value) {
            addCriterion("RESERVE <=", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveLike(String value) {
            addCriterion("RESERVE like", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveNotLike(String value) {
            addCriterion("RESERVE not like", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveIn(List<String> values) {
            addCriterion("RESERVE in", values, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveNotIn(List<String> values) {
            addCriterion("RESERVE not in", values, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveBetween(String value1, String value2) {
            addCriterion("RESERVE between", value1, value2, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveNotBetween(String value1, String value2) {
            addCriterion("RESERVE not between", value1, value2, "reserve");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNull() {
            addCriterion("OPER_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNotNull() {
            addCriterion("OPER_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOperDateEqualTo(String value) {
            addCriterion("OPER_DATE =", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotEqualTo(String value) {
            addCriterion("OPER_DATE <>", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThan(String value) {
            addCriterion("OPER_DATE >", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_DATE >=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThan(String value) {
            addCriterion("OPER_DATE <", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThanOrEqualTo(String value) {
            addCriterion("OPER_DATE <=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLike(String value) {
            addCriterion("OPER_DATE like", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotLike(String value) {
            addCriterion("OPER_DATE not like", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateIn(List<String> values) {
            addCriterion("OPER_DATE in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotIn(List<String> values) {
            addCriterion("OPER_DATE not in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateBetween(String value1, String value2) {
            addCriterion("OPER_DATE between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotBetween(String value1, String value2) {
            addCriterion("OPER_DATE not between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperTimeIsNull() {
            addCriterion("OPER_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOperTimeIsNotNull() {
            addCriterion("OPER_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOperTimeEqualTo(String value) {
            addCriterion("OPER_TIME =", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotEqualTo(String value) {
            addCriterion("OPER_TIME <>", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeGreaterThan(String value) {
            addCriterion("OPER_TIME >", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_TIME >=", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLessThan(String value) {
            addCriterion("OPER_TIME <", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLessThanOrEqualTo(String value) {
            addCriterion("OPER_TIME <=", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeLike(String value) {
            addCriterion("OPER_TIME like", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotLike(String value) {
            addCriterion("OPER_TIME not like", value, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeIn(List<String> values) {
            addCriterion("OPER_TIME in", values, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotIn(List<String> values) {
            addCriterion("OPER_TIME not in", values, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeBetween(String value1, String value2) {
            addCriterion("OPER_TIME between", value1, value2, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperTimeNotBetween(String value1, String value2) {
            addCriterion("OPER_TIME not between", value1, value2, "operTime");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNull() {
            addCriterion("OPER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNotNull() {
            addCriterion("OPER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOperIdEqualTo(String value) {
            addCriterion("OPER_ID =", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotEqualTo(String value) {
            addCriterion("OPER_ID <>", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThan(String value) {
            addCriterion("OPER_ID >", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_ID >=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThan(String value) {
            addCriterion("OPER_ID <", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThanOrEqualTo(String value) {
            addCriterion("OPER_ID <=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLike(String value) {
            addCriterion("OPER_ID like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotLike(String value) {
            addCriterion("OPER_ID not like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdIn(List<String> values) {
            addCriterion("OPER_ID in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotIn(List<String> values) {
            addCriterion("OPER_ID not in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdBetween(String value1, String value2) {
            addCriterion("OPER_ID between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotBetween(String value1, String value2) {
            addCriterion("OPER_ID not between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCfmTxnCodeIsNull() {
            addCriterion("CFM_TXN_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCfmTxnCodeIsNotNull() {
            addCriterion("CFM_TXN_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCfmTxnCodeEqualTo(String value) {
            addCriterion("CFM_TXN_CODE =", value, "cfmTxnCode");
            return (Criteria) this;
        }

        public Criteria andCfmTxnCodeNotEqualTo(String value) {
            addCriterion("CFM_TXN_CODE <>", value, "cfmTxnCode");
            return (Criteria) this;
        }

        public Criteria andCfmTxnCodeGreaterThan(String value) {
            addCriterion("CFM_TXN_CODE >", value, "cfmTxnCode");
            return (Criteria) this;
        }

        public Criteria andCfmTxnCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CFM_TXN_CODE >=", value, "cfmTxnCode");
            return (Criteria) this;
        }

        public Criteria andCfmTxnCodeLessThan(String value) {
            addCriterion("CFM_TXN_CODE <", value, "cfmTxnCode");
            return (Criteria) this;
        }

        public Criteria andCfmTxnCodeLessThanOrEqualTo(String value) {
            addCriterion("CFM_TXN_CODE <=", value, "cfmTxnCode");
            return (Criteria) this;
        }

        public Criteria andCfmTxnCodeLike(String value) {
            addCriterion("CFM_TXN_CODE like", value, "cfmTxnCode");
            return (Criteria) this;
        }

        public Criteria andCfmTxnCodeNotLike(String value) {
            addCriterion("CFM_TXN_CODE not like", value, "cfmTxnCode");
            return (Criteria) this;
        }

        public Criteria andCfmTxnCodeIn(List<String> values) {
            addCriterion("CFM_TXN_CODE in", values, "cfmTxnCode");
            return (Criteria) this;
        }

        public Criteria andCfmTxnCodeNotIn(List<String> values) {
            addCriterion("CFM_TXN_CODE not in", values, "cfmTxnCode");
            return (Criteria) this;
        }

        public Criteria andCfmTxnCodeBetween(String value1, String value2) {
            addCriterion("CFM_TXN_CODE between", value1, value2, "cfmTxnCode");
            return (Criteria) this;
        }

        public Criteria andCfmTxnCodeNotBetween(String value1, String value2) {
            addCriterion("CFM_TXN_CODE not between", value1, value2, "cfmTxnCode");
            return (Criteria) this;
        }

        public Criteria andQryTxnCodeIsNull() {
            addCriterion("QRY_TXN_CODE is null");
            return (Criteria) this;
        }

        public Criteria andQryTxnCodeIsNotNull() {
            addCriterion("QRY_TXN_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andQryTxnCodeEqualTo(String value) {
            addCriterion("QRY_TXN_CODE =", value, "qryTxnCode");
            return (Criteria) this;
        }

        public Criteria andQryTxnCodeNotEqualTo(String value) {
            addCriterion("QRY_TXN_CODE <>", value, "qryTxnCode");
            return (Criteria) this;
        }

        public Criteria andQryTxnCodeGreaterThan(String value) {
            addCriterion("QRY_TXN_CODE >", value, "qryTxnCode");
            return (Criteria) this;
        }

        public Criteria andQryTxnCodeGreaterThanOrEqualTo(String value) {
            addCriterion("QRY_TXN_CODE >=", value, "qryTxnCode");
            return (Criteria) this;
        }

        public Criteria andQryTxnCodeLessThan(String value) {
            addCriterion("QRY_TXN_CODE <", value, "qryTxnCode");
            return (Criteria) this;
        }

        public Criteria andQryTxnCodeLessThanOrEqualTo(String value) {
            addCriterion("QRY_TXN_CODE <=", value, "qryTxnCode");
            return (Criteria) this;
        }

        public Criteria andQryTxnCodeLike(String value) {
            addCriterion("QRY_TXN_CODE like", value, "qryTxnCode");
            return (Criteria) this;
        }

        public Criteria andQryTxnCodeNotLike(String value) {
            addCriterion("QRY_TXN_CODE not like", value, "qryTxnCode");
            return (Criteria) this;
        }

        public Criteria andQryTxnCodeIn(List<String> values) {
            addCriterion("QRY_TXN_CODE in", values, "qryTxnCode");
            return (Criteria) this;
        }

        public Criteria andQryTxnCodeNotIn(List<String> values) {
            addCriterion("QRY_TXN_CODE not in", values, "qryTxnCode");
            return (Criteria) this;
        }

        public Criteria andQryTxnCodeBetween(String value1, String value2) {
            addCriterion("QRY_TXN_CODE between", value1, value2, "qryTxnCode");
            return (Criteria) this;
        }

        public Criteria andQryTxnCodeNotBetween(String value1, String value2) {
            addCriterion("QRY_TXN_CODE not between", value1, value2, "qryTxnCode");
            return (Criteria) this;
        }

        public Criteria andActSerialNoIsNull() {
            addCriterion("ACT_SERIAL_NO is null");
            return (Criteria) this;
        }

        public Criteria andActSerialNoIsNotNull() {
            addCriterion("ACT_SERIAL_NO is not null");
            return (Criteria) this;
        }

        public Criteria andActSerialNoEqualTo(String value) {
            addCriterion("ACT_SERIAL_NO =", value, "actSerialNo");
            return (Criteria) this;
        }

        public Criteria andActSerialNoNotEqualTo(String value) {
            addCriterion("ACT_SERIAL_NO <>", value, "actSerialNo");
            return (Criteria) this;
        }

        public Criteria andActSerialNoGreaterThan(String value) {
            addCriterion("ACT_SERIAL_NO >", value, "actSerialNo");
            return (Criteria) this;
        }

        public Criteria andActSerialNoGreaterThanOrEqualTo(String value) {
            addCriterion("ACT_SERIAL_NO >=", value, "actSerialNo");
            return (Criteria) this;
        }

        public Criteria andActSerialNoLessThan(String value) {
            addCriterion("ACT_SERIAL_NO <", value, "actSerialNo");
            return (Criteria) this;
        }

        public Criteria andActSerialNoLessThanOrEqualTo(String value) {
            addCriterion("ACT_SERIAL_NO <=", value, "actSerialNo");
            return (Criteria) this;
        }

        public Criteria andActSerialNoLike(String value) {
            addCriterion("ACT_SERIAL_NO like", value, "actSerialNo");
            return (Criteria) this;
        }

        public Criteria andActSerialNoNotLike(String value) {
            addCriterion("ACT_SERIAL_NO not like", value, "actSerialNo");
            return (Criteria) this;
        }

        public Criteria andActSerialNoIn(List<String> values) {
            addCriterion("ACT_SERIAL_NO in", values, "actSerialNo");
            return (Criteria) this;
        }

        public Criteria andActSerialNoNotIn(List<String> values) {
            addCriterion("ACT_SERIAL_NO not in", values, "actSerialNo");
            return (Criteria) this;
        }

        public Criteria andActSerialNoBetween(String value1, String value2) {
            addCriterion("ACT_SERIAL_NO between", value1, value2, "actSerialNo");
            return (Criteria) this;
        }

        public Criteria andActSerialNoNotBetween(String value1, String value2) {
            addCriterion("ACT_SERIAL_NO not between", value1, value2, "actSerialNo");
            return (Criteria) this;
        }

        public Criteria andBookTypeIsNull() {
            addCriterion("BOOK_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andBookTypeIsNotNull() {
            addCriterion("BOOK_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andBookTypeEqualTo(String value) {
            addCriterion("BOOK_TYPE =", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeNotEqualTo(String value) {
            addCriterion("BOOK_TYPE <>", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeGreaterThan(String value) {
            addCriterion("BOOK_TYPE >", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeGreaterThanOrEqualTo(String value) {
            addCriterion("BOOK_TYPE >=", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeLessThan(String value) {
            addCriterion("BOOK_TYPE <", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeLessThanOrEqualTo(String value) {
            addCriterion("BOOK_TYPE <=", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeLike(String value) {
            addCriterion("BOOK_TYPE like", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeNotLike(String value) {
            addCriterion("BOOK_TYPE not like", value, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeIn(List<String> values) {
            addCriterion("BOOK_TYPE in", values, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeNotIn(List<String> values) {
            addCriterion("BOOK_TYPE not in", values, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeBetween(String value1, String value2) {
            addCriterion("BOOK_TYPE between", value1, value2, "bookType");
            return (Criteria) this;
        }

        public Criteria andBookTypeNotBetween(String value1, String value2) {
            addCriterion("BOOK_TYPE not between", value1, value2, "bookType");
            return (Criteria) this;
        }

        public Criteria andStsFlagIsNull() {
            addCriterion("STS_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andStsFlagIsNotNull() {
            addCriterion("STS_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andStsFlagEqualTo(String value) {
            addCriterion("STS_FLAG =", value, "stsFlag");
            return (Criteria) this;
        }

        public Criteria andStsFlagNotEqualTo(String value) {
            addCriterion("STS_FLAG <>", value, "stsFlag");
            return (Criteria) this;
        }

        public Criteria andStsFlagGreaterThan(String value) {
            addCriterion("STS_FLAG >", value, "stsFlag");
            return (Criteria) this;
        }

        public Criteria andStsFlagGreaterThanOrEqualTo(String value) {
            addCriterion("STS_FLAG >=", value, "stsFlag");
            return (Criteria) this;
        }

        public Criteria andStsFlagLessThan(String value) {
            addCriterion("STS_FLAG <", value, "stsFlag");
            return (Criteria) this;
        }

        public Criteria andStsFlagLessThanOrEqualTo(String value) {
            addCriterion("STS_FLAG <=", value, "stsFlag");
            return (Criteria) this;
        }

        public Criteria andStsFlagLike(String value) {
            addCriterion("STS_FLAG like", value, "stsFlag");
            return (Criteria) this;
        }

        public Criteria andStsFlagNotLike(String value) {
            addCriterion("STS_FLAG not like", value, "stsFlag");
            return (Criteria) this;
        }

        public Criteria andStsFlagIn(List<String> values) {
            addCriterion("STS_FLAG in", values, "stsFlag");
            return (Criteria) this;
        }

        public Criteria andStsFlagNotIn(List<String> values) {
            addCriterion("STS_FLAG not in", values, "stsFlag");
            return (Criteria) this;
        }

        public Criteria andStsFlagBetween(String value1, String value2) {
            addCriterion("STS_FLAG between", value1, value2, "stsFlag");
            return (Criteria) this;
        }

        public Criteria andStsFlagNotBetween(String value1, String value2) {
            addCriterion("STS_FLAG not between", value1, value2, "stsFlag");
            return (Criteria) this;
        }

        public Criteria andRelateBillnoIsNull() {
            addCriterion("RELATE_BILLNO is null");
            return (Criteria) this;
        }

        public Criteria andRelateBillnoIsNotNull() {
            addCriterion("RELATE_BILLNO is not null");
            return (Criteria) this;
        }

        public Criteria andRelateBillnoEqualTo(String value) {
            addCriterion("RELATE_BILLNO =", value, "relateBillno");
            return (Criteria) this;
        }

        public Criteria andRelateBillnoNotEqualTo(String value) {
            addCriterion("RELATE_BILLNO <>", value, "relateBillno");
            return (Criteria) this;
        }

        public Criteria andRelateBillnoGreaterThan(String value) {
            addCriterion("RELATE_BILLNO >", value, "relateBillno");
            return (Criteria) this;
        }

        public Criteria andRelateBillnoGreaterThanOrEqualTo(String value) {
            addCriterion("RELATE_BILLNO >=", value, "relateBillno");
            return (Criteria) this;
        }

        public Criteria andRelateBillnoLessThan(String value) {
            addCriterion("RELATE_BILLNO <", value, "relateBillno");
            return (Criteria) this;
        }

        public Criteria andRelateBillnoLessThanOrEqualTo(String value) {
            addCriterion("RELATE_BILLNO <=", value, "relateBillno");
            return (Criteria) this;
        }

        public Criteria andRelateBillnoLike(String value) {
            addCriterion("RELATE_BILLNO like", value, "relateBillno");
            return (Criteria) this;
        }

        public Criteria andRelateBillnoNotLike(String value) {
            addCriterion("RELATE_BILLNO not like", value, "relateBillno");
            return (Criteria) this;
        }

        public Criteria andRelateBillnoIn(List<String> values) {
            addCriterion("RELATE_BILLNO in", values, "relateBillno");
            return (Criteria) this;
        }

        public Criteria andRelateBillnoNotIn(List<String> values) {
            addCriterion("RELATE_BILLNO not in", values, "relateBillno");
            return (Criteria) this;
        }

        public Criteria andRelateBillnoBetween(String value1, String value2) {
            addCriterion("RELATE_BILLNO between", value1, value2, "relateBillno");
            return (Criteria) this;
        }

        public Criteria andRelateBillnoNotBetween(String value1, String value2) {
            addCriterion("RELATE_BILLNO not between", value1, value2, "relateBillno");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("DEPT_ID is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("DEPT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(String value) {
            addCriterion("DEPT_ID =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(String value) {
            addCriterion("DEPT_ID <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(String value) {
            addCriterion("DEPT_ID >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT_ID >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(String value) {
            addCriterion("DEPT_ID <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(String value) {
            addCriterion("DEPT_ID <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLike(String value) {
            addCriterion("DEPT_ID like", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotLike(String value) {
            addCriterion("DEPT_ID not like", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<String> values) {
            addCriterion("DEPT_ID in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<String> values) {
            addCriterion("DEPT_ID not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(String value1, String value2) {
            addCriterion("DEPT_ID between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(String value1, String value2) {
            addCriterion("DEPT_ID not between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andBankUserIsNull() {
            addCriterion("BANK_USER is null");
            return (Criteria) this;
        }

        public Criteria andBankUserIsNotNull() {
            addCriterion("BANK_USER is not null");
            return (Criteria) this;
        }

        public Criteria andBankUserEqualTo(String value) {
            addCriterion("BANK_USER =", value, "bankUser");
            return (Criteria) this;
        }

        public Criteria andBankUserNotEqualTo(String value) {
            addCriterion("BANK_USER <>", value, "bankUser");
            return (Criteria) this;
        }

        public Criteria andBankUserGreaterThan(String value) {
            addCriterion("BANK_USER >", value, "bankUser");
            return (Criteria) this;
        }

        public Criteria andBankUserGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_USER >=", value, "bankUser");
            return (Criteria) this;
        }

        public Criteria andBankUserLessThan(String value) {
            addCriterion("BANK_USER <", value, "bankUser");
            return (Criteria) this;
        }

        public Criteria andBankUserLessThanOrEqualTo(String value) {
            addCriterion("BANK_USER <=", value, "bankUser");
            return (Criteria) this;
        }

        public Criteria andBankUserLike(String value) {
            addCriterion("BANK_USER like", value, "bankUser");
            return (Criteria) this;
        }

        public Criteria andBankUserNotLike(String value) {
            addCriterion("BANK_USER not like", value, "bankUser");
            return (Criteria) this;
        }

        public Criteria andBankUserIn(List<String> values) {
            addCriterion("BANK_USER in", values, "bankUser");
            return (Criteria) this;
        }

        public Criteria andBankUserNotIn(List<String> values) {
            addCriterion("BANK_USER not in", values, "bankUser");
            return (Criteria) this;
        }

        public Criteria andBankUserBetween(String value1, String value2) {
            addCriterion("BANK_USER between", value1, value2, "bankUser");
            return (Criteria) this;
        }

        public Criteria andBankUserNotBetween(String value1, String value2) {
            addCriterion("BANK_USER not between", value1, value2, "bankUser");
            return (Criteria) this;
        }

        public Criteria andBankCfmDateIsNull() {
            addCriterion("BANK_CFM_DATE is null");
            return (Criteria) this;
        }

        public Criteria andBankCfmDateIsNotNull() {
            addCriterion("BANK_CFM_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andBankCfmDateEqualTo(String value) {
            addCriterion("BANK_CFM_DATE =", value, "bankCfmDate");
            return (Criteria) this;
        }

        public Criteria andBankCfmDateNotEqualTo(String value) {
            addCriterion("BANK_CFM_DATE <>", value, "bankCfmDate");
            return (Criteria) this;
        }

        public Criteria andBankCfmDateGreaterThan(String value) {
            addCriterion("BANK_CFM_DATE >", value, "bankCfmDate");
            return (Criteria) this;
        }

        public Criteria andBankCfmDateGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_CFM_DATE >=", value, "bankCfmDate");
            return (Criteria) this;
        }

        public Criteria andBankCfmDateLessThan(String value) {
            addCriterion("BANK_CFM_DATE <", value, "bankCfmDate");
            return (Criteria) this;
        }

        public Criteria andBankCfmDateLessThanOrEqualTo(String value) {
            addCriterion("BANK_CFM_DATE <=", value, "bankCfmDate");
            return (Criteria) this;
        }

        public Criteria andBankCfmDateLike(String value) {
            addCriterion("BANK_CFM_DATE like", value, "bankCfmDate");
            return (Criteria) this;
        }

        public Criteria andBankCfmDateNotLike(String value) {
            addCriterion("BANK_CFM_DATE not like", value, "bankCfmDate");
            return (Criteria) this;
        }

        public Criteria andBankCfmDateIn(List<String> values) {
            addCriterion("BANK_CFM_DATE in", values, "bankCfmDate");
            return (Criteria) this;
        }

        public Criteria andBankCfmDateNotIn(List<String> values) {
            addCriterion("BANK_CFM_DATE not in", values, "bankCfmDate");
            return (Criteria) this;
        }

        public Criteria andBankCfmDateBetween(String value1, String value2) {
            addCriterion("BANK_CFM_DATE between", value1, value2, "bankCfmDate");
            return (Criteria) this;
        }

        public Criteria andBankCfmDateNotBetween(String value1, String value2) {
            addCriterion("BANK_CFM_DATE not between", value1, value2, "bankCfmDate");
            return (Criteria) this;
        }

        public Criteria andPayMoneyIsNull() {
            addCriterion("PAY_MONEY is null");
            return (Criteria) this;
        }

        public Criteria andPayMoneyIsNotNull() {
            addCriterion("PAY_MONEY is not null");
            return (Criteria) this;
        }

        public Criteria andPayMoneyEqualTo(BigDecimal value) {
            addCriterion("PAY_MONEY =", value, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyNotEqualTo(BigDecimal value) {
            addCriterion("PAY_MONEY <>", value, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyGreaterThan(BigDecimal value) {
            addCriterion("PAY_MONEY >", value, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_MONEY >=", value, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyLessThan(BigDecimal value) {
            addCriterion("PAY_MONEY <", value, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_MONEY <=", value, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyIn(List<BigDecimal> values) {
            addCriterion("PAY_MONEY in", values, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyNotIn(List<BigDecimal> values) {
            addCriterion("PAY_MONEY not in", values, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_MONEY between", value1, value2, "payMoney");
            return (Criteria) this;
        }

        public Criteria andPayMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_MONEY not between", value1, value2, "payMoney");
            return (Criteria) this;
        }

        public Criteria andAcceptDateIsNull() {
            addCriterion("ACCEPT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andAcceptDateIsNotNull() {
            addCriterion("ACCEPT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andAcceptDateEqualTo(String value) {
            addCriterion("ACCEPT_DATE =", value, "acceptDate");
            return (Criteria) this;
        }

        public Criteria andAcceptDateNotEqualTo(String value) {
            addCriterion("ACCEPT_DATE <>", value, "acceptDate");
            return (Criteria) this;
        }

        public Criteria andAcceptDateGreaterThan(String value) {
            addCriterion("ACCEPT_DATE >", value, "acceptDate");
            return (Criteria) this;
        }

        public Criteria andAcceptDateGreaterThanOrEqualTo(String value) {
            addCriterion("ACCEPT_DATE >=", value, "acceptDate");
            return (Criteria) this;
        }

        public Criteria andAcceptDateLessThan(String value) {
            addCriterion("ACCEPT_DATE <", value, "acceptDate");
            return (Criteria) this;
        }

        public Criteria andAcceptDateLessThanOrEqualTo(String value) {
            addCriterion("ACCEPT_DATE <=", value, "acceptDate");
            return (Criteria) this;
        }

        public Criteria andAcceptDateLike(String value) {
            addCriterion("ACCEPT_DATE like", value, "acceptDate");
            return (Criteria) this;
        }

        public Criteria andAcceptDateNotLike(String value) {
            addCriterion("ACCEPT_DATE not like", value, "acceptDate");
            return (Criteria) this;
        }

        public Criteria andAcceptDateIn(List<String> values) {
            addCriterion("ACCEPT_DATE in", values, "acceptDate");
            return (Criteria) this;
        }

        public Criteria andAcceptDateNotIn(List<String> values) {
            addCriterion("ACCEPT_DATE not in", values, "acceptDate");
            return (Criteria) this;
        }

        public Criteria andAcceptDateBetween(String value1, String value2) {
            addCriterion("ACCEPT_DATE between", value1, value2, "acceptDate");
            return (Criteria) this;
        }

        public Criteria andAcceptDateNotBetween(String value1, String value2) {
            addCriterion("ACCEPT_DATE not between", value1, value2, "acceptDate");
            return (Criteria) this;
        }

        public Criteria andRpTypeIsNull() {
            addCriterion("RP_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andRpTypeIsNotNull() {
            addCriterion("RP_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andRpTypeEqualTo(String value) {
            addCriterion("RP_TYPE =", value, "rpType");
            return (Criteria) this;
        }

        public Criteria andRpTypeNotEqualTo(String value) {
            addCriterion("RP_TYPE <>", value, "rpType");
            return (Criteria) this;
        }

        public Criteria andRpTypeGreaterThan(String value) {
            addCriterion("RP_TYPE >", value, "rpType");
            return (Criteria) this;
        }

        public Criteria andRpTypeGreaterThanOrEqualTo(String value) {
            addCriterion("RP_TYPE >=", value, "rpType");
            return (Criteria) this;
        }

        public Criteria andRpTypeLessThan(String value) {
            addCriterion("RP_TYPE <", value, "rpType");
            return (Criteria) this;
        }

        public Criteria andRpTypeLessThanOrEqualTo(String value) {
            addCriterion("RP_TYPE <=", value, "rpType");
            return (Criteria) this;
        }

        public Criteria andRpTypeLike(String value) {
            addCriterion("RP_TYPE like", value, "rpType");
            return (Criteria) this;
        }

        public Criteria andRpTypeNotLike(String value) {
            addCriterion("RP_TYPE not like", value, "rpType");
            return (Criteria) this;
        }

        public Criteria andRpTypeIn(List<String> values) {
            addCriterion("RP_TYPE in", values, "rpType");
            return (Criteria) this;
        }

        public Criteria andRpTypeNotIn(List<String> values) {
            addCriterion("RP_TYPE not in", values, "rpType");
            return (Criteria) this;
        }

        public Criteria andRpTypeBetween(String value1, String value2) {
            addCriterion("RP_TYPE between", value1, value2, "rpType");
            return (Criteria) this;
        }

        public Criteria andRpTypeNotBetween(String value1, String value2) {
            addCriterion("RP_TYPE not between", value1, value2, "rpType");
            return (Criteria) this;
        }

        public Criteria andRpMemoIsNull() {
            addCriterion("RP_MEMO is null");
            return (Criteria) this;
        }

        public Criteria andRpMemoIsNotNull() {
            addCriterion("RP_MEMO is not null");
            return (Criteria) this;
        }

        public Criteria andRpMemoEqualTo(String value) {
            addCriterion("RP_MEMO =", value, "rpMemo");
            return (Criteria) this;
        }

        public Criteria andRpMemoNotEqualTo(String value) {
            addCriterion("RP_MEMO <>", value, "rpMemo");
            return (Criteria) this;
        }

        public Criteria andRpMemoGreaterThan(String value) {
            addCriterion("RP_MEMO >", value, "rpMemo");
            return (Criteria) this;
        }

        public Criteria andRpMemoGreaterThanOrEqualTo(String value) {
            addCriterion("RP_MEMO >=", value, "rpMemo");
            return (Criteria) this;
        }

        public Criteria andRpMemoLessThan(String value) {
            addCriterion("RP_MEMO <", value, "rpMemo");
            return (Criteria) this;
        }

        public Criteria andRpMemoLessThanOrEqualTo(String value) {
            addCriterion("RP_MEMO <=", value, "rpMemo");
            return (Criteria) this;
        }

        public Criteria andRpMemoLike(String value) {
            addCriterion("RP_MEMO like", value, "rpMemo");
            return (Criteria) this;
        }

        public Criteria andRpMemoNotLike(String value) {
            addCriterion("RP_MEMO not like", value, "rpMemo");
            return (Criteria) this;
        }

        public Criteria andRpMemoIn(List<String> values) {
            addCriterion("RP_MEMO in", values, "rpMemo");
            return (Criteria) this;
        }

        public Criteria andRpMemoNotIn(List<String> values) {
            addCriterion("RP_MEMO not in", values, "rpMemo");
            return (Criteria) this;
        }

        public Criteria andRpMemoBetween(String value1, String value2) {
            addCriterion("RP_MEMO between", value1, value2, "rpMemo");
            return (Criteria) this;
        }

        public Criteria andRpMemoNotBetween(String value1, String value2) {
            addCriterion("RP_MEMO not between", value1, value2, "rpMemo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 06 15:07:04 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.HMFS_JZ_REFUND
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}