package org.fbi.hmfsjz.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.hmfsjz.repository.model.HmfsJzIrt;
import org.fbi.hmfsjz.repository.model.HmfsJzIrtExample;

public interface HmfsJzIrtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    int countByExample(HmfsJzIrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    int deleteByExample(HmfsJzIrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    int insert(HmfsJzIrt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    int insertSelective(HmfsJzIrt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    List<HmfsJzIrt> selectByExample(HmfsJzIrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    HmfsJzIrt selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    int updateByExampleSelective(@Param("record") HmfsJzIrt record, @Param("example") HmfsJzIrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    int updateByExample(@Param("record") HmfsJzIrt record, @Param("example") HmfsJzIrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    int updateByPrimaryKeySelective(HmfsJzIrt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 22 13:20:44 CST 2014
     */
    int updateByPrimaryKey(HmfsJzIrt record);
}