package org.fbi.hmfsjz.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.hmfsjz.repository.model.HmfsJzDraw;
import org.fbi.hmfsjz.repository.model.HmfsJzDrawExample;

public interface HmfsJzDrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int countByExample(HmfsJzDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int deleteByExample(HmfsJzDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int insert(HmfsJzDraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int insertSelective(HmfsJzDraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    List<HmfsJzDraw> selectByExample(HmfsJzDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    HmfsJzDraw selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int updateByExampleSelective(@Param("record") HmfsJzDraw record, @Param("example") HmfsJzDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int updateByExample(@Param("record") HmfsJzDraw record, @Param("example") HmfsJzDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int updateByPrimaryKeySelective(HmfsJzDraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int updateByPrimaryKey(HmfsJzDraw record);
}