package org.fbi.hmfsjz.repository.dao;

import org.fbi.hmfsjz.repository.model.HmfsJzActTxn;
import org.fbi.hmfsjz.repository.model.HmfsJzActTxnExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HmfsJzActTxnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_ACT_TXN
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    int countByExample(HmfsJzActTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_ACT_TXN
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    int deleteByExample(HmfsJzActTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_ACT_TXN
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_ACT_TXN
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    int insert(HmfsJzActTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_ACT_TXN
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    int insertSelective(HmfsJzActTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_ACT_TXN
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    List<HmfsJzActTxn> selectByExample(HmfsJzActTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_ACT_TXN
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    HmfsJzActTxn selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_ACT_TXN
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    int updateByExampleSelective(@Param("record") HmfsJzActTxn record, @Param("example") HmfsJzActTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_ACT_TXN
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    int updateByExample(@Param("record") HmfsJzActTxn record, @Param("example") HmfsJzActTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_ACT_TXN
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    int updateByPrimaryKeySelective(HmfsJzActTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JZ_ACT_TXN
     *
     * @mbggenerated Wed Nov 06 15:07:04 CST 2013
     */
    int updateByPrimaryKey(HmfsJzActTxn record);
}